apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: lynis-logfile
spec:
  schemaVersion: 42
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: Lynis Logfile
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*lynis-logfile.*/
      current:
        text: cmd-check-lynis-logfile-sudo
        value: cmd-check-lynis-logfile-sudo
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: Lynis Logfile - Hardening Index
    type: timeseries
    gridPos:
      h: 8
      w: 24
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        max: 100
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: hardening_index
      refId: hardening_index
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: hardening_index

  - title: Lynis Logfile - Findings and Suggestions
    type: timeseries
    gridPos:
      h: 8
      w: 24
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: findings
      refId: findings
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: findings

    - alias: suggestions
      refId: suggestions
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: suggestions
