#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

"""See the check's README for more details."""

import argparse
import base64
import json
import sys

import lib.args
import lib.base
import lib.redfish
import lib.lftest
import lib.txt
import lib.url
from lib.globals import STATE_CRIT, STATE_OK, STATE_UNKNOWN, STATE_WARN

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2026040801'

DESCRIPTION = """Checks the System Event Log (SEL) of Redfish-compatible servers via the Redfish API.
Alerts based on the severity of log entries. Entries can be filtered by regex."""

DEFAULT_INSECURE = True
DEFAULT_NO_PROXY = False
DEFAULT_TIMEOUT = 8
DEFAULT_URL = 'https://localhost:5000'


def parse_args():
    """Parse command line arguments using argparse."""
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V',
        '--version',
        action='version',
        version=f'%(prog)s: v{__version__} by {__author__}',
    )

    parser.add_argument(
        '--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '--insecure',
        help='This option explicitly allows to perform "insecure" SSL connections. '
        'Default: %(default)s',
        dest='INSECURE',
        action='store_true',
        default=DEFAULT_INSECURE,
    )

    parser.add_argument(
        '--no-proxy',
        help='Do not use a proxy. Default: %(default)s',
        dest='NO_PROXY',
        action='store_true',
        default=DEFAULT_NO_PROXY,
    )

    parser.add_argument(
        '--password',
        help='Redfish API password.',
        dest='PASSWORD',
    )

    parser.add_argument(
        '--test',
        help='For unit tests. Needs "path-to-stdout-file,path-to-stderr-file,expected-retc".',
        dest='TEST',
        type=lib.args.csv,
    )

    parser.add_argument(
        '--timeout',
        help='Network timeout in seconds. Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    parser.add_argument(
        '--url',
        help='Redfish API URL. Default: %(default)s',
        dest='URL',
        default=DEFAULT_URL,
    )

    parser.add_argument(
        '--username',
        help='Redfish API username.',
        dest='USERNAME',
    )

    args, _ = parser.parse_known_args()
    return args


def main():
    """The main function. Hier spielt die Musik."""

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # fetch data
    if args.TEST is None:
        if not args.URL.startswith('http'):
            lib.base.cu('--url parameter has to start with "http://" or https://".')

        # Authorization (if needed)
        header = {}
        header['Accept'] = 'application/json'
        if args.USERNAME and args.PASSWORD:
            auth = f'{args.USERNAME}:{args.PASSWORD}'
            encoded_auth = lib.txt.to_text(base64.b64encode(lib.txt.to_bytes(auth)))
            header['Authorization'] = f'Basic {encoded_auth}'

        # get the vendor to know which entry point to use
        result = lib.base.coe(
            lib.url.fetch_json(
                f'{args.URL}/redfish/v1/',
                header=header,
                insecure=args.INSECURE,
                no_proxy=args.NO_PROXY,
                timeout=args.TIMEOUT,
            )
        )
        vendor = lib.redfish.get_vendor(result)

        if vendor == 'supermicro':
            entry_point = 'Systems'
        else:
            entry_point = 'Managers'

        # Entry point: Get the main data
        result = lib.base.coe(
            lib.url.fetch_json(
                f'{args.URL}/redfish/v1/{entry_point}',
                header=header,
                insecure=args.INSECURE,
                no_proxy=args.NO_PROXY,
                timeout=args.TIMEOUT,
            )
        )
    else:
        # do not call the command, put in test data
        args.TEST[0] += '-v1'
        stdout, _, _ = lib.lftest.test(args.TEST)
        result = json.loads(stdout)
        vendor = lib.redfish.get_vendor(result)

        args.TEST[0] += '-managers'
        stdout, _, _ = lib.lftest.test(args.TEST)
        result = json.loads(stdout)

    # "Members": [
    #     {
    #         "@odata.id": "/redfish/v1/Managers/BMC"
    #     }
    # ],
    if len(result.get('Members', [])) == 0:
        lib.base.cu('Nothing to check, no Redfish members found.')

    # init some vars
    msg = ''
    state = STATE_OK

    if vendor == 'generic':
        sel_path = '/LogServices/Log/Entries'
    elif vendor in ['avigilon']:  # which is a relabeled dell
        sel_path = '/LogServices'
    elif vendor in ['ami']:
        sel_path = '/LogServices/BIOS/Entries'
    elif vendor in ['cisco']:
        sel_path = '/LogServices/SEL/Entries'
    elif vendor in ['dell']:
        sel_path = '/LogServices/Sel/Entries'
    elif vendor in ['hpe', 'hp']:
        sel_path = '/LogServices/IML/Entries'
    elif vendor in ['lenovo']:
        sel_path = '/LogServices/ActiveLog/Entries'
    elif vendor in ['supermicro']:
        sel_path = '/LogServices/Log1/Entries'
    elif vendor in ['ts_fujitsu']:
        sel_path = '/LogServices/SystemEventLog/Entries'
    else:
        sel_path = ''

    member_count = 0
    # fetch and analyze data by following the "Members" found
    for member in result.get('Members', []):
        if not sel_path:
            continue
        member_count += 1
        if args.TEST is None:
            # For example {https://localhost:5000} {/redfish/v1/Managers/BMC} {/LogServices/Log/Entries}
            sel = lib.base.coe(
                lib.url.fetch_json(
                    f'{args.URL}{member["@odata.id"]}{sel_path}',
                    header=header,
                    insecure=args.INSECURE,
                    no_proxy=args.NO_PROXY,
                    timeout=args.TIMEOUT,
                )
            )
        else:
            args.TEST[0] += '-vendor'
            stdout, _, _ = lib.lftest.test(args.TEST)
            sel = json.loads(stdout)
        member_msg, member_state = lib.redfish.get_manager_logservices_sel_entries(sel)
        if member_msg:
            msg += f'{member["@odata.id"]}\n{member_msg}\n\n'
            state = lib.base.get_worst(state, member_state)

    members = lib.txt.pluralize('member', member_count)
    if state == STATE_CRIT:
        msg = (
            f'Checked SEL on {member_count} {members}. There are critical errors.\n\n'
        ) + msg
    elif state == STATE_WARN:
        msg = (
            f'Checked SEL on {member_count} {members}. There are warnings.\n\n'
        ) + msg
    else:
        msg = (f'Everything is ok, checked SEL on {member_count} {members}.\n\n') + msg

    # over and out
    lib.base.oao(msg, state, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception:
        lib.base.cu()
