#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""See the check's README for more details.
"""

import argparse  # pylint: disable=C0413
import sys  # pylint: disable=C0413

import lib.base  # pylint: disable=C0413
import lib.librenms  # pylint: disable=C0413
import lib.version  # pylint: disable=C0413
from lib.globals import STATE_OK, STATE_UNKNOWN  # pylint: disable=C0413

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2023042305'

DESCRIPTION = '''This check displays LibreNMS instance information, using its API. This is not a
                 "is there a new version out there" g itself (if running the Git version).'''

DEFAULT_INSECURE = False
DEFAULT_NO_PROXY = False
DEFAULT_TIMEOUT = 3
DEFAULT_URL = 'http://localhost'


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='%(prog)s: v{} by {}'.format(__version__, __author__)
    )

    parser.add_argument(
        '--insecure',
        help='This option explicitly allows to perform "insecure" SSL '
             'connections. Default: %(default)s',
        dest='INSECURE',
        action='store_true',
        default=DEFAULT_INSECURE,
    )

    parser.add_argument(
        '--no-proxy',
        help='Do not use a proxy. Default: %(default)s',
        dest='NO_PROXY',
        action='store_true',
        default=DEFAULT_NO_PROXY,
    )

    parser.add_argument(
        '--timeout',
        help='Network timeout in seconds. Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    parser.add_argument(
        '--token',
        help='LibreNMS API token',
        dest='TOKEN',
        required=True,
    )

    parser.add_argument(
        '--url',
        help='LibreNMS API URL. Default: %(default)s',
        dest='URL',
        default=DEFAULT_URL,
    )

    return parser.parse_args()


def main():
    """The main function. Hier spielt die Musik.
    """

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # init some vars
    msg = ''
    state = STATE_OK
    perfdata = ''

    # return LibreNMS instance information
    result = lib.librenms.get_data(args, '/api/v0/system')
    result = result['system'][0]

    # since 22.7.0-33:
    # {'local_ver': '22.7.0-33-g3d65e722a', 'local_sha': '3d65e722a621776eb7ff592455bd63fa5637b98b',
    # 'local_date': '1659276599', 'local_branch': 'master', 'github': None, 
    # 'db_schema': '2022_07_03_1947_add_app_data (244)', 'php_ver': '8.1.8', 'python_ver': '3.6.8',
    # 'database_ver': 'MariaDB 10.6.8-MariaDB', 'rrdtool_ver': '1.7.0', 'netsnmp_ver': '5.8'}

    msg += 'LibreNMS {}'.format(result['local_ver'])
    if 'local_branch' in result:
        msg += ' (Git: {})'.format(result['local_branch'])
    msg += ', '
    msg += 'DB-Schema {}, '.format(result['db_schema'])
    try:
        msg += result['database_ver']
    except:
        msg += result['mysql_ver']
    msg += '{}, '.format(result['netsnmp_ver'])
    msg += 'PHP {}, '.format(result['php_ver'])
    msg += 'Python {}, '.format(result['python_ver'])
    msg += 'RRD-Tool {}'.format(result['rrdtool_ver'])

    perfdata += lib.base.get_perfdata('librenms-version', lib.version.version2float(result['local_ver']), None, None, None, 0, None)
    try:
        perfdata += lib.base.get_perfdata('db-version', lib.version.version2float(result['database_ver']), None, None, None, 0, None)
    except:
        perfdata += lib.base.get_perfdata('db-version', lib.version.version2float(result['mysql_ver']), None, None, None, 0, None)
    perfdata += lib.base.get_perfdata('netsnmp-version', lib.version.version2float(result['netsnmp_ver']), None, None, None, 0, None)
    perfdata += lib.base.get_perfdata('php-version', lib.version.version2float(result['php_ver']), None, None, None, 0, None)
    perfdata += lib.base.get_perfdata('python-version', lib.version.version2float(result['python_ver']), None, None, None, 0, None)
    perfdata += lib.base.get_perfdata('rrdtool-version', lib.version.version2float(result['rrdtool_ver']), None, None, None, 0, None)

    # over and out
    lib.base.oao(msg, state, perfdata)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base.cu()
