#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

"""See the check's README for more details."""

import argparse
import sys

import lib.args
import lib.base
import lib.db_mysql
import lib.human
from lib.globals import STATE_OK, STATE_UNKNOWN, STATE_WARN

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2026040801'

DESCRIPTION = """Checks the table definition cache size in MySQL/MariaDB. Alerts if the cache is too
small to hold definitions for all tables, causing repeated disk reads."""

DEFAULT_DEFAULTS_FILE = '/var/spool/icinga2/.my.cnf'
DEFAULT_DEFAULTS_GROUP = 'client'
DEFAULT_TIMEOUT = 3


def parse_args():
    """Parse command line arguments using argparse."""
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V',
        '--version',
        action='version',
        version=f'%(prog)s: v{__version__} by {__author__}',
    )

    parser.add_argument(
        '--always-ok',
        help=lib.args.help('--always-ok'),
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '--defaults-file',
        help='MySQL/MariaDB cnf file to read parameters like user, host and password from (instead of specifying them on the command line). '
        'Example: `/var/spool/icinga2/.my.cnf`. '
        'Default: %(default)s.',
        dest='DEFAULTS_FILE',
        default=DEFAULT_DEFAULTS_FILE,
    )

    parser.add_argument(
        '--defaults-group',
        help=lib.args.help('--defaults-group') + ' Default: %(default)s',
        dest='DEFAULTS_GROUP',
        default=DEFAULT_DEFAULTS_GROUP,
    )

    parser.add_argument(
        '--timeout',
        help=lib.args.help('--timeout') + ' Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    args, _ = parser.parse_known_args()
    return args


def get_vars(conn):
    # Do not implement `get_all_vars()`, just fetch the ones we need for this check.
    # Without the GLOBAL modifier, SHOW VARIABLES displays the values that are used for
    # the current connection to MariaDB.
    sql = """
        show global variables
        where variable_name like 'table_definition_cache'
            ;
          """
    return lib.base.coe(lib.db_mysql.select(conn, sql))


def main():
    """The main function. Hier spielt die Musik."""

    # logic taken from mysqltuner.pl:mysql_stats(), section # Table definition cache, v1.9.8
    # including variable names

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    mysql_connection = {
        'defaults_file': args.DEFAULTS_FILE,
        'defaults_group': args.DEFAULTS_GROUP,
        'timeout': args.TIMEOUT,
    }
    conn = lib.base.coe(lib.db_mysql.connect(mysql_connection))
    lib.base.coe(lib.db_mysql.check_select_privileges(conn))

    myvar = lib.db_mysql.lod2dict(get_vars(conn))

    # init some vars
    state = STATE_OK
    perfdata = ''

    # calculations
    mycalc = {}
    sql = 'select count(*) as cnt from information_schema.tables'
    nbtables = lib.base.coe(lib.db_mysql.select(conn, sql))
    lib.db_mysql.close(conn)
    mycalc['total_tables'] = nbtables[0]['cnt']

    # Table definition cache
    if myvar.get('table_definition_cache', None) is not None:
        if int(myvar['table_definition_cache']) == -1:
            msg = (
                f'table_definition_cache'
                f' ({myvar["table_definition_cache"]})'
                f' is in autosizing mode.'
            )
        elif int(myvar['table_definition_cache']) < int(mycalc['total_tables']):
            state = STATE_WARN
            msg = (
                f'table_definition_cache'
                f' ({myvar["table_definition_cache"]})'
                f' is lower than number of tables'
                f' ({mycalc["total_tables"]})'
                f'{lib.base.state2str(state, prefix=" ")}. '
            )
            msg += (
                f'Set table_definition_cache >'
                f' {mycalc["total_tables"]}'
                f' or to -1 (autosizing if supported).'
            )
        else:
            msg = (
                f'Everything is ok. table_definition_cache'
                f' ({myvar["table_definition_cache"]})'
                f' is upper than number of tables'
                f' ({mycalc["total_tables"]}).'
            )
    else:
        msg = 'Everything is ok.'

    perfdata += lib.base.get_perfdata(
        'mysql_table_definition_cache',
        myvar['table_definition_cache'],
        _min=0,
    )
    perfdata += lib.base.get_perfdata(
        'mysql_total_tables',
        mycalc['total_tables'],
        _min=0,
    )

    # over and out
    lib.base.oao(msg, state, perfdata, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception:
        lib.base.cu()
