#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_CRIT, STATE_OK, STATE_UNKNOWN, STATE_WARN

COMMON = '--url http://example.com'


TESTS = [
    {
        'id': 'ok-all-channels-healthy',
        'test': 'stdout/all-channels-healthy,,0',
        'params': COMMON,
        'assert-retc': STATE_OK,
        'assert-in': [
            'Everything is ok on host-name SN 20961563.',
            'ch1 ! Temperature       !       ! 28.9C',
            'ch2 ! Relative humidity !       ! 15.8%RH',
            'ch3 ! Dew point         !       ! 0.4C',
            'ch4 ! n/a               !       ! Error 2n/a',
        ],
    },
    {
        'id': 'warn-temp-high-and-dew-low-default-severity',
        'test': 'stdout/alarms-temp-high-and-dew-low,,0',
        'params': COMMON,
        'assert-retc': STATE_WARN,
        'assert-in': [
            'There are warnings on Web Sensor SN 17965562.',
            'ch1 ! Temperature          ! high  ! 27.3C [WARNING]',
            'ch3 ! Dew point            ! low   ! 13.7C [WARNING]',
        ],
    },
    {
        'id': 'unknown-invalid-severity-value',
        'test': 'stdout/alarms-temp-high-and-dew-low,,0',
        'params': f'{COMMON} --severity gobbledygook',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': [
            'Unknown states on Web Sensor SN 17965562.',
            'ch1 ! Temperature          ! high  ! 27.3C [UNKNOWN]',
            'ch3 ! Dew point            ! low   ! 13.7C [UNKNOWN]',
        ],
    },
    {
        'id': 'crit-severity-crit-maps-all-alarms-to-crit',
        'test': 'stdout/alarms-temp-high-and-dew-low,,0',
        'params': f'{COMMON} --severity crit',
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'There are critical errors on Web Sensor SN 17965562',
            'ch1 ! Temperature          ! high  ! 27.3C [CRITICAL]',
            'ch3 ! Dew point            ! low   ! 13.7C [CRITICAL]',
        ],
    },
    {
        'id': 'crit-generic-crit-wins-when-listed-first',
        'test': 'stdout/alarms-temp-high-and-dew-low,,0',
        'params': f'{COMMON} --severity crit --severity temp:warn',
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'ch1 ! Temperature          ! high  ! 27.3C [CRITICAL]',
            'ch3 ! Dew point            ! low   ! 13.7C [CRITICAL]',
        ],
    },
    {
        'id': 'crit-specific-temp-warn-wins-when-listed-first',
        'test': 'stdout/alarms-temp-high-and-dew-low,,0',
        'params': f'{COMMON} --severity temp:warn --severity crit',
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'ch1 ! Temperature          ! high  ! 27.3C [WARNING]',
            'ch3 ! Dew point            ! low   ! 13.7C [CRITICAL]',
        ],
    },
    {
        'id': 'crit-custom-humidity-rules',
        'test': 'stdout/alarm-humidity-high-custom-channels,,0',
        'params': (
            f'{COMMON} --severity humi:high:ok --severity humi:low:warn '
            '--severity crit'
        ),
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'There are critical errors on My device SN 13940001.',
            'ch1 ! Humidity    ! high  ! 34.94%RH',
            'ch3 ! n/a         ! high  ! 22.49x [CRITICAL]',
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../cometsystem'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
