#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""See the check's README for more details.
"""

import argparse  # pylint: disable=C0413
import sys  # pylint: disable=C0413

import lib.base  # pylint: disable=C0413
import lib.cache  # pylint: disable=C0413
import lib.disk  # pylint: disable=C0413
import lib.time  # pylint: disable=C0413
import lib.url  # pylint: disable=C0413
import lib.version  # pylint: disable=C0413
from lib.globals import (STATE_CRIT, STATE_OK,  # pylint: disable=C0413
                          STATE_UNKNOWN, STATE_WARN)

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2023042305'

DESCRIPTION = 'This plugin lets you track if server updates are available.'

DEFAULT_CACHE_EXPIRE = 24 # hours
DEFAULT_PATH         = '/var/www/html/matomo'


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='%(prog)s: v{} by {}'.format(__version__, __author__)
    )

    parser.add_argument(
        '--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '--cache-expire',
        help='The amount of time after which the update check cache expires, in hours. Default: %(default)s',
        dest='CACHE_EXPIRE',
        type=int,
        default=DEFAULT_CACHE_EXPIRE,
    )

    parser.add_argument(
        '--path',
        help='Local path to your Matomo/Piwik installation, typically within your Webserver\'s Document Root. Default: %(default)s',
        dest='PATH',
        default=DEFAULT_PATH,
    )

    return parser.parse_args()


def get_installed_version(path):
    # matomo/Version.php: const version='3.13.4';
    success, matomo_version = lib.disk.grep_file(path + '/core/Version.php', r"N = '(.*?)'")
    if not success:
        return (success, matomo_version)
    if matomo_version:
        # 3.13.4
        return (True, matomo_version)
    return (True, False)


def get_latest_version(expire):
    # get version online, but first from cache
    latest_version = lib.cache.get('matomo-version')
    if latest_version:
        return (True, latest_version)

    # nothing found in cache, get the latest version from github
    success, latest_version = lib.url.get_latest_version_from_github('matomo-org', 'matomo')
    if not success:
        return (success, latest_version)

    if '-' in latest_version:
        # it is a version like "3.13.4-b1" or "3.13.2-rc2", so the installed
        # version is better, and don't save this pre-release to the cache
        return (True, '0.0.0')

    lib.cache.set('matomo-version', latest_version, lib.time.now() + expire)
    return (True, latest_version)


def main():
    """The main function. Hier spielt die Musik.
    """

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # fetch data
    installed_version = lib.base.coe(get_installed_version(args.PATH))
    latest_version = lib.base.coe(get_latest_version(args.CACHE_EXPIRE*60*60))

    # over and out
    if lib.version.version(installed_version) >= lib.version.version(latest_version):
        lib.base.oao('Matomo v{} is up to date'.format(installed_version), STATE_OK)
    lib.base.oao('Matomo v{} installed, Matomo v{} available'.format(
        installed_version,
        latest_version,
    ), STATE_WARN, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base.cu()
