#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_OK

TESTS = [
    {
        'id': 'ok-one-conference-active',
        'test': 'stdout/one-conference-active,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            '18 total participants, 1 conference, Stress Level 0.01092, 93 JVM threads, 1.3Mbps download, 603.4Kbps upload',
        ],
    },
    {
        'id': 'ok-one-conference-idle',
        'test': 'stdout/one-conference-idle,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            '18 total participants, 1 conference, Stress Level 0.0, 53 JVM threads, 0.0bps download, 0.0bps upload',
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../jitsi-videobridge-stats'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
