version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '11:11'
      timezone: 'Europe/Zurich'

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '11:11'
      timezone: 'Europe/Zurich'
