#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_WARN
import lib.lftest


TESTS = [
    {
        'id': 'warn-power-supplies-warning',
        'test': 'stdout/power-supplies-warning,,0',
        'params': '--device-id=1 --password=pass --url=https://localhost --username=admin',
        'assert-retc': STATE_WARN,
        'assert-in': [
            'There are warnings.',
            'UUID       ! Location    ! Manufacturer ! Model         ! SerialNumber         '
            '! Produced   ! In (MV) ! Out (MV) ! Temp ! Health    ! Running  ',
            '-----------+-------------+--------------+---------------+----------------------'
            '+------------+---------+----------+------+-----------+----------',
            '23:23.0.0  ! CTE0.PSU0   ! HUAWEI       ! PAC2000S12-BG ! 12345678             '
            '! 2020-08-20 ! 0       ! 0        ! 0    ! [OK]      ! [OK]     ',
            '23:23.0.1  ! CTE0.PSU1   ! HUAWEI       ! PAC2000S12-BG ! 12345678             '
            '! 2020-08-20 ! 0       ! 0        ! 0    ! [OK]      ! [OK]     ',
            '23:23.0.2  ! CTE0.PSU2   ! HUAWEI       ! PAC2000S12-BG ! 12345678             '
            '! 2020-08-21 ! 0       ! 0        ! 0    ! [OK]      ! [OK]     ',
            '23:23.0.3  ! CTE0.PSU3   ! HUAWEI       ! PAC2000S12-BG ! 12345678             '
            '! 2020-08-20 ! 0       ! 0        ! 0    ! [OK]      ! [OK]     ',
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../huawei-dorado-power'

    def test(self):
        for t in TESTS:
            with self.subTest(id=t['id']):
                lib.lftest.run(self, self.check, t)


if __name__ == '__main__':
    unittest.main()
