repos:
  - repo: 'https://github.com/digitalpulp/pre-commit-php'
    rev: '1.4.0'
    hooks:
      - id: 'php-lint-all'

  - repo: 'https://github.com/gitleaks/gitleaks'
    rev: 'v8.30.0'
    hooks:
      - id: 'gitleaks'

  - repo: 'https://github.com/jumanjihouse/pre-commit-hooks'
    rev: '3.0.0'
    hooks:
      - id: 'shellcheck'

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v6.0.0'
    hooks:
      - id: 'check-added-large-files'
      - id: 'check-merge-conflict'
      - id: 'check-yaml'
      - id: 'end-of-file-fixer'
      - id: 'trailing-whitespace'

  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: 'v0.15.12'
    hooks:
      - id: 'ruff-check'
        args: ['--fix']
      - id: 'ruff-format'

  - repo: 'https://github.com/pylint-dev/pylint'
    rev: 'v4.0.5'
    hooks:
      - id: 'pylint'

  - repo: 'https://github.com/PyCQA/bandit'
    rev: '1.9.4'
    hooks:
      - id: 'bandit'
        args: ['-c', 'pyproject.toml', '--severity-level=low', '--confidence-level=low']
        additional_dependencies: ['bandit[toml]']
        types_or: ['python']

  - repo: 'https://github.com/jendrikseipp/vulture'
    rev: 'v2.16'
    hooks:
      - id: 'vulture'
        args: ['--min-confidence=80']
        types_or: ['python']
