[tox]
envlist = py39, py310, py311, py312, py313, py314
skip_missing_interpreters = true

[testenv]
deps =
    beautifulsoup4
    linuxfabrik-lib
    lxml
    psutil
    python-keystoneclient
    python-novaclient
    python-swiftclient
    pyyaml
    smbprotocol
    vici
    xmltodict
commands =
    python tools/run-unit-tests {posargs}
