apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: mysql-traffic
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: MySQL Traffic
  uid: linuxfabrik-monitoring-plugins-mysql-traffic
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*mysql-traffic.*/
      current:
        text: cmd-check-mysql-traffic
        value: cmd-check-mysql-traffic
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: MySQL Traffic - Bytes (lifetime)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        min: 0
        unit: bytes
      overrides:
      - matcher:
          id: byName
          options: mysql_bytes_received
        properties:
        - id: displayName
          value: Bytes_received
      - matcher:
          id: byName
          options: mysql_bytes_sent
        properties:
        - id: displayName
          value: Bytes_sent
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_bytes_received
      refId: mysql_bytes_received
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_bytes_received

    - alias: mysql_bytes_sent
      refId: mysql_bytes_sent
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_bytes_sent

  - title: MySQL Traffic - Command Counters (lifetime)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: short
      overrides:
      - matcher:
          id: byName
          options: mysql_com_select
        properties:
        - id: displayName
          value: Com_select
      - matcher:
          id: byName
          options: mysql_com_insert
        properties:
        - id: displayName
          value: Com_insert
      - matcher:
          id: byName
          options: mysql_com_update
        properties:
        - id: displayName
          value: Com_update
      - matcher:
          id: byName
          options: mysql_com_delete
        properties:
        - id: displayName
          value: Com_delete
      - matcher:
          id: byName
          options: mysql_com_replace
        properties:
        - id: displayName
          value: Com_replace
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_com_select
      refId: mysql_com_select
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_com_select

    - alias: mysql_com_insert
      refId: mysql_com_insert
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_com_insert

    - alias: mysql_com_update
      refId: mysql_com_update
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_com_update

    - alias: mysql_com_delete
      refId: mysql_com_delete
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_com_delete

    - alias: mysql_com_replace
      refId: mysql_com_replace
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_com_replace

  - title: MySQL Traffic - Connections / Questions (lifetime)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: short
      overrides:
      - matcher:
          id: byName
          options: mysql_connections
        properties:
        - id: displayName
          value: Connections
      - matcher:
          id: byName
          options: mysql_questions
        properties:
        - id: displayName
          value: Questions
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_connections
      refId: mysql_connections
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_connections

    - alias: mysql_questions
      refId: mysql_questions
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_questions

  - title: MySQL Traffic - Queries per Second
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        min: 0
        unit: short
      overrides:
      - matcher:
          id: byName
          options: mysql_qps
        properties:
        - id: displayName
          value: Questions / Uptime
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_qps
      refId: mysql_qps
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_qps

  - title: MySQL Traffic - Read / Write Ratio
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        max: 100
        min: 0
        unit: percent
      overrides:
      - matcher:
          id: byName
          options: mysql_pct_reads
        properties:
        - id: displayName
          value: reads
      - matcher:
          id: byName
          options: mysql_pct_writes
        properties:
        - id: displayName
          value: writes
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_pct_reads
      refId: mysql_pct_reads
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_pct_reads

    - alias: mysql_pct_writes
      refId: mysql_pct_writes
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_pct_writes

  - title: MySQL Traffic - Server Uptime
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: s
      overrides:
      - matcher:
          id: byName
          options: mysql_uptime
        properties:
        - id: displayName
          value: Uptime (seconds; resets to 0 on server restart)
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_uptime
      refId: mysql_uptime
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_uptime
