[cmd-check-network-errors]
dashboard = "Network Errors"
panelId = "2,3"
orgId = ""
dashboarduid = "network-errors"
; just show the first panels, until repeatable works correctly
; repeatable = "yes"
; nmetrics = "10"

[cmd-check-network-errors-windows]
dashboard = "Network Errors - Windows"
panelId = "2,3"
orgId = ""
dashboarduid = "network-errors"
; just show the first panels, until repeatable works correctly
; repeatable = "yes"
; nmetrics = "10"

[cmd-check-network-errors-windows-python]
dashboard = "Network Errors - Windows"
panelId = "2,3"
orgId = ""
dashboarduid = "network-errors"
; just show the first panels, until repeatable works correctly
; repeatable = "yes"
; nmetrics = "10"
