#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_OK, STATE_UNKNOWN, STATE_WARN

TESTS = [
    {
        'id': 'warn-frontend-sessions-high',
        'test': 'stdout/frontend-sessions-high,,0',
        'assert-retc': STATE_WARN,
        'assert-in': [
            'frontend-https FRONTEND: 2666 sessions (88.9%) [WARNING], frontend-https-8443 FRONTEND: STOP',
        ],
    },
    {
        'id': 'unknown-malformed-status',
        'test': 'stdout/malformed-status,,0',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['Malformed HAProxy status info.'],
    },
    {
        'id': 'ok-all-backends-up',
        'test': 'stdout/all-backends-up,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            'Everything is ok.',
            'Proxy name          ! Server name ! Sessions ! RqBytes   ! RspBytes ! Rsp5xx ! Rq/s ! Status',
            '--------------------+-------------+----------+-----------+----------+--------+------+-------',
            'frontend-https      ! FRONTEND    ! 1/3000   ! 267.3MiB  ! 439.1MiB ! 588    ! 0    ! OPEN  ',
            'frontend-https-8443 ! FRONTEND    ! 0/3000   ! 1004.8KiB ! 14.8MiB  ! 72     ! 0    ! OPEN  ',
            'rabbitmq-35671-5672 ! FRONTEND    ! 0/3000   ! 0.0B      ! 0.0B     !        ! 0    ! OPEN  ',
            'rabbitmq-35671-5672 ! srvmq01     ! 0        ! 0.0B      ! 0.0B     !        !      ! UP    ',
            'rabbitmq-35671-5672 ! BACKEND     ! 0/300    ! 0.0B      ! 0.0B     !        !      ! UP    ',
            'srvvcs01-80         ! srvvcs01    ! 0        ! 111.2MiB  ! 361.6MiB ! 5      !      ! UP    ',
            'srvvcs01-80         ! BACKEND     ! 0/300    ! 111.2MiB  ! 361.6MiB ! 96     !      ! UP    ',
            'srvvcs01-5050       ! srvvcs01    ! 0        ! 150.2MiB  ! 137.4KiB ! 0      !      ! UP    ',
            'srvvcs01-5050       ! BACKEND     ! 0/300    ! 150.2MiB  ! 137.4KiB ! 0      !      ! UP    ',
            'srvlog01-9000       ! srvlog01    ! 0        ! 990.6KiB  ! 14.7MiB  ! 0      !      ! UP    ',
            'srvlog01-9000       ! BACKEND     ! 0/300    ! 990.6KiB  ! 14.7MiB  ! 0      !      ! UP    ',
            'srvapp01-6082       ! srvapp01    ! 0        ! 973.6KiB  ! 2.8MiB   ! 0      !      ! UP    ',
            'srvapp01-6082       ! BACKEND     ! 0/300    ! 974.0KiB  ! 2.8MiB   ! 3      !      ! UP    ',
            'srvapp01-6081       ! srvapp01    ! 0        ! 976.0KiB  ! 2.6MiB   ! 0      !      ! UP    ',
            'srvapp01-6081       ! BACKEND     ! 0/300    ! 976.2KiB  ! 2.6MiB   ! 1      !      ! UP    ',
            'srvapp01-6090       ! srvapp01    ! 0        ! 979.6KiB  ! 3.2MiB   ! 0      !      ! UP    ',
            'srvapp01-6090       ! BACKEND     ! 0/300    ! 979.8KiB  ! 3.2MiB   ! 1      !      ! UP    ',
            'srvapp01-6083       ! srvapp01    ! 0        ! 2.0MiB    ! 65.8MiB  ! 0      !      ! UP    ',
            'srvapp01-6083       ! BACKEND     ! 0/300    ! 2.0MiB    ! 65.8MiB  ! 5      !      ! UP    ',
            'srvapp01-6080       ! srvapp01    ! 0        ! 1018.8KiB ! 2.8MiB   ! 0      !      ! UP    ',
            'srvapp01-6080       ! BACKEND     ! 0/300    ! 1019.4KiB ! 2.8MiB   ! 4      !      ! UP    ',
            'stats               ! FRONTEND    ! 1/3000   ! 71.2KiB   ! 1.7MiB   ! 3      ! 1    ! OPEN  ',
            'stats               ! BACKEND     ! 0/300    ! 71.2KiB   ! 1.7MiB   ! 3      !      ! UP',
        ],
    },
    {
        'id': 'warn-frontend-sessions-high-lengthy',
        'test': 'stdout/frontend-sessions-high,,0',
        'params': '--lengthy',
        'assert-retc': STATE_WARN,
        'assert-in': [
            'frontend-https FRONTEND: 2666 sessions (88.9%) [WARNING], frontend-https-8443 FRONTEND: STOP',
        ],
    },
    {
        'id': 'unknown-malformed-status-lengthy',
        'test': 'stdout/malformed-status,,0',
        'params': '--lengthy',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['Malformed HAProxy status info.'],
    },
    {
        'id': 'ok-all-backends-up-lengthy',
        'test': 'stdout/all-backends-up,,0',
        'params': '--lengthy',
        'assert-retc': STATE_OK,
        'assert-in': [
            'Everything is ok.',
            'Proxy name',
        ],
    },

    # #835: without --ignore, an on-demand certbot backend in MAINT/DOWN
    # produces a WARN; --ignore='^certbot/' filters the whole proxy and
    # the check comes back OK while still reporting the rest of the
    # HAProxy topology. The regex is case-sensitive by default (matching
    # the lib.args --match / --ignore-regex convention), so
    # --ignore='^CERTBOT/' does NOT match; the user opts into
    # case-insensitive matching with the inline `(?i)` flag.
    {
        'id': 'warn-certbot-backend-down',
        'test': 'stdout/certbot-backend-down,,0',
        'assert-retc': STATE_WARN,
        'assert-in': [
            'certbot certbot_challenge: MAINT',
            'certbot BACKEND: DOWN',
        ],
    },
    {
        'id': 'ok-certbot-ignored',
        'test': 'stdout/certbot-backend-down,,0',
        'params': "--ignore='^certbot/'",
        'assert-retc': STATE_OK,
        'assert-in': ['Everything is ok.', 'web', 'FRONTEND'],
        'assert-not-in': ['certbot'],
    },
    {
        'id': 'warn-certbot-default-case-sensitive',
        'test': 'stdout/certbot-backend-down,,0',
        # Uppercase pattern must NOT match lowercase certbot: the regex
        # default is case-sensitive, so this ignore is a no-op and the
        # certbot proxy still triggers a WARN.
        'params': "--ignore='^CERTBOT/'",
        'assert-retc': STATE_WARN,
        'assert-in': ['certbot BACKEND: DOWN'],
    },
    {
        'id': 'ok-certbot-ignored-case-insensitive-opt-in',
        'test': 'stdout/certbot-backend-down,,0',
        # Opt into case-insensitive matching with the inline `(?i)`
        # flag, which is the lib.args convention for --match /
        # --ignore-regex parameters.
        'params': "--ignore='(?i)^certbot/'",
        'assert-retc': STATE_OK,
        'assert-in': ['Everything is ok.'],
        'assert-not-in': ['certbot certbot_challenge: MAINT'],
    },
    {
        'id': 'unknown-ignore-invalid-regex',
        'test': 'stdout/certbot-backend-down,,0',
        'params': "--ignore='('",
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['Invalid regular expression'],
    },

    # --username and --password were removed in favour of HTTP basic
    # auth embedded in the URL itself. The flags stay registered with
    # argparse.SUPPRESS so we can hard-UNKNOWN here with a clear
    # migration pointer instead of letting parse_known_args silently
    # swallow them and surface a 401 from the haproxy stats endpoint.
    {
        'id': 'unknown-legacy-username',
        'test': 'stdout/all-backends-up,,0',
        'params': '--username=stats',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': [
            '--username and --password were removed.',
            'https://user:linuxfabrik@host',
        ],
    },
    {
        'id': 'unknown-legacy-password',
        'test': 'stdout/all-backends-up,,0',
        'params': '--password=linuxfabrik',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': [
            '--username and --password were removed.',
            'https://user:linuxfabrik@host',
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../haproxy-status'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
