#! /usr/bin/env python2
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://git.linuxfabrik.ch/linuxfabrik-icinga-plugins/checks-linux/-/blob/master/CONTRIBUTING.md

import os

activate_this = False
venv_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'monitoring-plugins-venv2')
if os.path.exists(venv_path):
    activate_this = os.path.join(venv_path, 'bin/activate_this.py')

if os.getenv('MONITORING_PLUGINS_VENV2'):
    activate_this = os.path.join(os.getenv('MONITORING_PLUGINS_VENV2') + 'bin/activate_this.py')

if activate_this and os.path.isfile(activate_this):
    exec(open(activate_this).read(), {'__file__': activate_this})


__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2021082501'

DESCRIPTION = 'Checks the mail queue.'

cmd = 'mailq'       # `mailq` for `exim` is an alias for `exim -bq`

DEFAULT_WARN  =    2     # mails
DEFAULT_CRIT  =  250     # mails


#====================
from lib.globals2 import *

import lib.args2
import lib.base2

import argparse
import re


def parse_args():
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument('-V', '--version',
        action='version',
        version='{0}: v{1} by {2}'.format('%(prog)s', __version__, __author__)
        )

    parser.add_argument('--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
        )

    parser.add_argument('-c', '--critical',
        help='Set the critical threshold for mails in the queue. Default: %(default)s',
        dest='CRIT',
        type=int,
        default=DEFAULT_CRIT,
        )

    parser.add_argument('--test',
        help='For unit tests. Needs "path-to-stdout-file,path-to-stderr-file,expected-retc".',
        dest='TEST',
        type=lib.args2.csv,
        )

    parser.add_argument('-w', '--warning',
        help='Set the warning threshold for mails in the queue. Default: %(default)s',
        dest='WARN',
        type=int,
        default=DEFAULT_WARN,
        )

    return parser.parse_args()


def main():
    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit as e:
        exit(STATE_UNKNOWN)

    if args.TEST == None:
        stdout, stderr, retc = lib.base2.coe(lib.base2.shell_exec(cmd))
    else:
        # do not call the command, put in test data
        if args.TEST[0] and os.path.isfile(args.TEST[0]):
            f = open(args.TEST[0], 'r')
            stdout = f.read()
            f.close()
        else:
            stdout = args.TEST[0]
        if args.TEST[1] and os.path.isfile(args.TEST[1]):
            f = open(args.TEST[1], 'r')
            stderr = f.read()
            f.close()
        else:
            stderr = args.TEST[1]
        retc = args.TEST[2]

    mailq_err_msg = None
    if (stderr):
        # does mailq report something unusual?
        mailq_err_msg = stderr.strip()

    # count the mails in the queue
    mailq_count = 0
    stdout = stdout.strip()
    if stdout and stdout != 'Mail queue is empty' and stdout != '0 mails to deliver':
        # "-- 2 Kbytes in 3 Requests."
        mailq_count = re.search(r' in (.*) Requests?\.', stdout)
        if mailq_count:
            mailq_count = int(mailq_count.group(1).strip())
        else:
            # other mailq version? "17 mails to deliver"
            mailq_count = re.search(r'(.*) mails to deliver', stdout)
            if mailq_count:
                mailq_count = int(mailq_count.group(1).strip())
            else:
                # exim? for now, just count the lines (could be done better in the future)
                mailq_count = stdout.count('\n')

    msg = ''
    perfdata = ''

    if mailq_err_msg:
        msg += '{}. '.format(mailq_err_msg)
    if mailq_count:
        msg += '{} {} to deliver.'.format(mailq_count, lib.base2.pluralize('mail', mailq_count))
    else:
        msg += 'Mail queue is empty.'

    perfdata += lib.base2.get_perfdata('mailq', mailq_count, None, args.WARN, args.CRIT, 0, None)

    state = lib.base2.get_state(mailq_count, args.WARN, args.CRIT, operator='ge')
    if mailq_err_msg:
        state = lib.base2.get_worst(state, STATE_WARN)

    lib.base2.oao(msg, state, perfdata, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        lib.base2.cu()