#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import os
import shutil
import sys
import tempfile

sys.path.insert(0, '..')

import unittest

import lib.base
import lib.lftest
import lib.shell
from lib.globals import STATE_CRIT, STATE_OK, STATE_UNKNOWN, STATE_WARN

TESTS = [
    {
        'id': 'ok-five-clients-four-users',
        'test': 'stdout/five-clients-four-users,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            '5 users connected to OpenVPN Server.',
            'user1@linuxfabrik.ch',
            'user2@linuxfabrik.ch',
            'user3@linuxfabrik.ch',
            'user4@linuxfabrik.ch',
        ],
    },
    {
        'id': 'warn-above-warn-threshold',
        'test': 'stdout/five-clients-four-users,,0',
        'params': '--warning 4',
        'assert-retc': STATE_WARN,
        'assert-in': ['5 users connected to OpenVPN Server.'],
    },
    {
        'id': 'crit-above-crit-threshold',
        'test': 'stdout/five-clients-four-users,,0',
        'params': '--warning 3 --critical 4',
        'assert-retc': STATE_CRIT,
        'assert-in': ['5 users connected to OpenVPN Server.'],
    },
    # Recorded from OpenVPN 2.7.7 (Copr) on Rocky 8 with `proto udp6`: client01 connects
    # over IPv4 (printed as IPv4-mapped address), client02 over IPv6 to ::1.
    {
        'id': 'ok-parses-status-version-1',
        'test': 'stdout/openvpn27-v1-ipv4-and-ipv6-client,,0',
        'assert-retc': STATE_OK,
        'assert-regex': r'client01 +! 192\.168\.100\.157 +! 192\.168\.42\.3 ',
        'assert-in': ['2 users connected to OpenVPN Server.', '! ::1 ', '192.168.42.2'],
        'assert-not-in': ['udp6'],
    },
    {
        'id': 'ok-parses-status-version-2',
        'test': 'stdout/openvpn27-v2-ipv4-and-ipv6-client,,0',
        'assert-retc': STATE_OK,
        'assert-regex': r'client01 +! 192\.168\.100\.157 +! 192\.168\.42\.3 ',
        'assert-in': ['2 users connected to OpenVPN Server.', '! ::1 ', '192.168.42.2'],
        'assert-not-in': ['udp6'],
    },
    {
        'id': 'ok-parses-status-version-3',
        'test': 'stdout/openvpn27-v3-ipv4-and-ipv6-client,,0',
        'assert-retc': STATE_OK,
        'assert-regex': r'client01 +! 192\.168\.100\.157 +! 192\.168\.42\.3 ',
        'assert-in': ['2 users connected to OpenVPN Server.', '! ::1 ', '192.168.42.2'],
        'assert-not-in': ['udp6'],
    },
    {
        'id': 'ok-strips-udp4-prefix',
        'test': 'stdout/openvpn27-v2-one-udp4-client,,0',
        'assert-retc': STATE_OK,
        'assert-regex': r'client01 +! 192\.168\.100\.157 +! 192\.168\.42\.2 ',
        'assert-in': ['1 user connected to OpenVPN Server.'],
        'assert-not-in': ['udp4'],
    },
    {
        'id': 'ok-empty-file-while-openvpn-rewrites-it',
        'test': 'stdout/empty-file,,0',
        'assert-retc': STATE_OK,
        'assert-in': ['0 users connected to OpenVPN Server.'],
    },
    {
        'id': 'unknown-not-a-status-file',
        'test': 'stdout/openvpn-log-instead-of-status,,0',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['Unknown status file format.'],
    },
]


class TestCheck(unittest.TestCase):
    check = '../openvpn-client-list'


lib.lftest.attach_tests(TestCheck, TESTS)


class TestPathConfinement(unittest.TestCase):
    """A --filename outside /var/log is refused, so a root-run plugin cannot be
    turned into an arbitrary file read (GHSA-f54c-p5vg-mr5c). Invoked without
    --test so the real file-reading path and its confinement run."""

    def setUp(self):
        self.scratch_dir = tempfile.mkdtemp(prefix='openvpn-confine-')
        self.scratch_file = os.path.join(self.scratch_dir, 'status.log')
        with open(self.scratch_file, 'w', encoding='utf-8') as handle:
            handle.write('CLIENT_LIST,secret,203.0.113.5:1194,10.8.0.2,\n')

    def tearDown(self):
        shutil.rmtree(self.scratch_dir, ignore_errors=True)

    def test_filename_outside_var_log_is_refused(self):
        stdout, _, retc = lib.base.coe(
            lib.shell.shell_exec(
                ['../openvpn-client-list', f'--filename={self.scratch_file}']
            )
        )
        self.assertEqual(retc, STATE_UNKNOWN)
        self.assertIn('Refusing to read', stdout)
        self.assertNotIn('secret', stdout)


if __name__ == '__main__':
    unittest.main()
