apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: redfish-storage
spec:
  schemaVersion: 42
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: Redfish Storage
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*redfish-storage.*/
      current:
        text: cmd-check-redfish-storage
        value: cmd-check-redfish-storage
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: Component Counts
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - min
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: drives
      refId: drives
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: drives

    - alias: drives_not_ok
      refId: drives_not_ok
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: drives_not_ok

    - alias: volumes
      refId: volumes
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: volumes

    - alias: volumes_not_ok
      refId: volumes_not_ok
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: volumes_not_ok

    - alias: storage_controllers
      refId: storage_controllers
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: storage_controllers

    - alias: storage_controllers_not_ok
      refId: storage_controllers_not_ok
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: storage_controllers_not_ok


  - title: Drive Media Life Left
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        max: 100
        unit: percent
    options:
      legend:
        calcs:
        - min
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: $tag_metric
      refId: media_life_left
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - metric
        type: tag
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '=~'
        value: /_media_life_left$/


  - title: Drive Power-On Hours
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: h
    options:
      legend:
        calcs:
        - min
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: $tag_metric
      refId: power_on_hours
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - metric
        type: tag
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '=~'
        value: /_power_on_hours$/
