#! /usr/bin/env python2
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://git.linuxfabrik.ch/linuxfabrik-icinga-plugins/checks-linux/-/blob/master/CONTRIBUTING.md

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2020050101'

DESCRIPTION = 'Checks the used inode space in percent, default on "/", "/tmp" and "/boot".'

DEFAULT_WARN  = 90
DEFAULT_CRIT  = 95
DEFAULT_MOUNT = '/, /tmp, /boot'

#====================
from lib.globals2 import *

import argparse
import os
from traceback import print_exc

import lib.base2


def parse_args():
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument('-V', '--version',
        action='version',
        version='{0}: v{1} by {2}'.format('%(prog)s', __version__, __author__)
        )

    parser.add_argument('--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
        )

    parser.add_argument('-c', '--critical',
        help='Set the critical threshold inode usage percentage. Default: %(default)s',
        dest='CRIT',
        type=float,
        default=DEFAULT_CRIT,
        )

    parser.add_argument('--mount',
        help='The mount point. Default: "%(default)s"',
        dest='MOUNT',
        type=lambda s: [str(item).strip() for item in s.split(',')],
        default=DEFAULT_MOUNT,
        )

    parser.add_argument('-w', '--warning',
        help='Set the warning threshold inode usage percentage. Default: %(default)s',
        dest='WARN',
        type=float,
        default=DEFAULT_WARN,
        )

    return parser.parse_args()


def main():
    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit as e:
        exit(STATE_UNKNOWN)

    msg = ''
    perfdata = ''
    state = STATE_OK

    for mount in args.MOUNT:
        try:
            st = os.statvfs(mount)
            inodes_total = float(st.f_files)
            inodes_free = float(st.f_ffree)
            inodes_used = round((inodes_total - inodes_free) / inodes_total * 100, 1)

            msg += '{} {}%, '.format(mount, inodes_used)
            perfdata += lib.base2.get_perfdata(mount, inodes_used, '%', args.WARN, args.CRIT, 0, 100)

            if inodes_used >= args.CRIT:
                state = lib.base2.get_worst(state, STATE_CRIT)
                msg = msg[:-2] + ' (CRIT), '
            elif inodes_used >= args.WARN:
                state = lib.base2.get_worst(state, STATE_WARN)
                msg = msg[:-2] + ' (WARN), '
        except Exception as e:
            lib.base2.oao('Something seems to be wrong with the input parameter. The error was: {}'.format(e), STATE_UNKNOWN)

    lib.base2.oao(msg[:-2], state, perfdata, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print_exc()
        exit(STATE_UNKNOWN)
