#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_CRIT, STATE_WARN
import lib.lftest


TESTS = [
    {
        'id': 'crit-no-license-over-limits',
        'test': 'stdout/no-license-over-limits,,0',
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'Max 20 connections, no license, last hour: 7/17/19 views [CRITICAL] and 3/13/18 edits [WARNING]',
        ],
    },
    {
        'id': 'warn-license-expired',
        'test': 'stdout/license-expired,,0',
        'assert-retc': STATE_WARN,
        'assert-in': ['Max 100 connections, licensed (expired) [WARNING], '],
    },
]


class TestCheck(unittest.TestCase):

    check = '../onlyoffice-stats'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
