version = "1.0"

[[packages]]
name = "bash"
comment = "Added by 'versionlock add' command on 2026-08-10 13:51:57"

[[packages.conditions]]
key = "evr"
comparator = "="
value = "5.3.9-3.fc44"

[[packages]]
name = "glibc"
comment = "Added by 'versionlock add' command on 2026-08-10 13:51:57"

[[packages.conditions]]
key = "evr"
comparator = "="
value = "2.43-8.fc44"

[[packages]]
name = "curl"
comment = "Added by 'versionlock exclude' command on 2026-08-10 13:51:57"

[[packages.conditions]]
key = "evr"
comparator = "!="
value = "8.18.0-4.fc44"

[[packages.conditions]]
key = "evr"
comparator = "!="
value = "8.18.0-8.fc44"
