#! /usr/bin/env python2
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://git.linuxfabrik.ch/linuxfabrik-icinga-plugins/checks-linux/-/blob/master/CONTRIBUTING.md

"""Have a look at the check's README for further details.
"""

import os

# considering a virtual environment
ACTIVATE_THIS = False
venv_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'monitoring-plugins-venv2')
if os.path.exists(venv_path):
    ACTIVATE_THIS = os.path.join(venv_path, 'bin/activate_this.py')

if os.getenv('MONITORING_PLUGINS_VENV2'):
    ACTIVATE_THIS = os.path.join(os.getenv('MONITORING_PLUGINS_VENV2') + 'bin/activate_this.py')

if ACTIVATE_THIS and os.path.isfile(ACTIVATE_THIS):
    exec(open(ACTIVATE_THIS).read(), {'__file__': ACTIVATE_THIS}) # pylint: disable=W0122


import argparse # pylint: disable=C0413
import re # pylint: disable=C0413
import sys # pylint: disable=C0413
from traceback import print_exc # pylint: disable=C0413

import lib.base2 # pylint: disable=C0413
from lib.globals2 import STATE_OK, STATE_UNKNOWN, STATE_WARN # pylint: disable=C0413


__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2021073001'

DESCRIPTION = 'Checks the ownership (owner and group, both have to be names) of a list of files.'

command = 'stat {path}'

# sorted by path
DEFAULT_FILES = [
    'root:root,/boot/grub/grub.conf',
    'root:root,/boot/grub2/grub.cfg',
    'root:root,/boot/grub2/grubenv',
    'root:root,/boot/grub2/user.cfg',
    'root:root,/etc/anacrontab',
    'root:root,/etc/at.allow',
    'root:root,/etc/cron.allow',
    'root:root,/etc/cron.d',
    'root:root,/etc/cron.daily',
    'root:root,/etc/cron.hourly',
    'root:root,/etc/cron.monthly',
    'root:root,/etc/cron.weekly',
    'root:root,/etc/crontab',
    'graylog:graylog,/etc/graylog/certs',
    'root:root,/etc/group',
    'root:root,/etc/group-',
    #'root:root,/etc/gshadow',      different on Debian and Ubuntu
    #'root:root,/etc/gshadow-',     different on Debian and Ubuntu
    'root:root,/etc/hosts.allow',
    'root:root,/etc/hosts.deny',
    'root:root,/etc/issue',
    'root:root,/etc/issue.net',
    'lool:lool,/etc/loolwsd/loolwsd.xml',
    'root:root,/etc/motd',
    'root:named,/etc/named.conf',
    'root:root,/etc/passwd',
    'root:root,/etc/passwd-',
    #'root:root,/etc/shadow',       different on Debian and Ubuntu
    #'root:root,/etc/shadow-',      different on SLES (15)
    'root:root,/etc/ssh/sshd_config',
    'vdsm:kvm,/home/ovirt',
    'root:root,/tmp',
    'hnet:hnet,/var/hnet',
    'unbound:unbound,/var/lib/unbound/root.key',
    'ldap:ldap,/var/run/openldap',
]


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='{0}: v{1} by {2}'.format('%(prog)s', __version__, __author__)
    )

    parser.add_argument(
        '--filename',
        help='File to be checked, in the format `owner:group,path` (repeatable).',
        action='append',
        dest='FILES',
        default=DEFAULT_FILES,
    )

    return parser.parse_args()


def main():
    """The main function. Hier spielt die Musik.
    """

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    state = STATE_OK
    msg = ''
    cnt = 0
    table_values = []

    for file in args.FILES:
        if not file:
            continue
        try:
            file = file.split(',')
            path = file[1]
        except:
            lib.base2.oao('--filename parameter seems to be in the wrong format.', STATE_UNKNOWN)
        try:
            expected_owner, expected_group = file[0].split(':')
        except:
            lib.base2.oao('--filename parameter seems to be in the wrong format.', STATE_UNKNOWN)

        cmd = command.format(path=path)
        # execute the shell command and return its result and exit code
        stdout, stderr, retc = lib.base2.coe(lib.base2.shell_exec(cmd))

        for line in stdout.splitlines():
            if not line.startswith('Access: ('):
                continue
            # Access: (0644/-rw-r--r--)  Uid: (  982/ unbound)   Gid: (  981/ unbound)
            # Access: (0600/-rw-------)  Uid: ( 1000/markus.frei)   Gid: ( 1000/markus.frei)
            found_owner = re.search(r'Uid: .*?\/(.*)\).*Gid:', line).group(1).strip()
            found_group = re.search(r'Gid: .*\/(.*)\)', line).group(1).strip()
            if expected_owner != found_owner or expected_group != found_group:
                file_state = STATE_WARN
            else:
                file_state = STATE_OK
            cnt += 1

            state = lib.base2.get_worst(file_state, state)
            table_values.append({
                'file': path,
                'expected': '{}:{}'.format(expected_owner, expected_group),
                'found': '{}:{}{}'.format(found_owner, found_group, lib.base2.state2str(file_state, prefix=' ')),
                })

    # create output
    if cnt == 0:
        lib.base2.oao('No files checked.', state)

    if state == STATE_OK:
        msg = 'Everything is ok.\n\n'
    else:
        msg = 'One or more problems with owners or groups.\n\n'
    if len(table_values) > 0:
        msg += lib.base2.get_table(
            table_values,
            ['file', 'expected', 'found'],
            header=['Path', 'Expected', 'Found'],
            )

    # over and out
    lib.base2.oao(msg, state)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        print_exc()
        sys.exit(STATE_UNKNOWN)
