#! /usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""Have a look at the check's README for further details.
"""

import os

# considering a virtual environment
ACTIVATE_THIS = False
venv_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'monitoring-plugins-venv3')
if os.path.exists(venv_path):
    ACTIVATE_THIS = os.path.join(venv_path, 'bin/activate_this.py')

if os.getenv('MONITORING_PLUGINS_VENV3'):
    ACTIVATE_THIS = os.path.join(os.getenv('MONITORING_PLUGINS_VENV3') + 'bin/activate_this.py')

if ACTIVATE_THIS and os.path.isfile(ACTIVATE_THIS):
    exec(open(ACTIVATE_THIS).read(), {'__file__': ACTIVATE_THIS}) # pylint: disable=W0122


import argparse # pylint: disable=C0413
import sys # pylint: disable=C0413

import lib.base3 # pylint: disable=C0413
import lib.db_mysql3 # pylint: disable=C0413
import lib.human3 # pylint: disable=C0413
from lib.globals3 import STATE_OK, STATE_UNKNOWN, STATE_WARN # pylint: disable=C0413


__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2022062101'

DESCRIPTION = """Checks if many joins per day without indexes were executed on MySQL/MariaDB."""

DEFAULT_HOSTNAME = '127.0.0.1'
DEFAULT_PORT = '3306'
DEFAULT_PASSWORD = ''
DEFAULT_USERNAME = 'root'


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='{0}: v{1} by {2}'.format('%(prog)s', __version__, __author__)
    )

    parser.add_argument(
        '--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '-H', '--hostname',
        help='MySQL/MariaDB hostname. Default: %(default)s',
        dest='HOSTNAME',
        default=DEFAULT_HOSTNAME,
    )

    parser.add_argument(
        '-p', '--password',
        help='Use the indicated password to authenticate the connection. Default: %(default)s',
        dest='PASSWORD',
        default=DEFAULT_PASSWORD,
    )

    parser.add_argument(
        '--port',
        help='MySQL/MariaDB port. Default: %(default)s',
        dest='PORT',
        type=int,
        default=DEFAULT_PORT,
    )

    parser.add_argument(
        '-u', '--username',
        help='MySQL/MariaDB username. Default: %(default)s',
        dest='USERNAME',
        default=DEFAULT_USERNAME,
    )

    return parser.parse_args()


def get_vars(conn):
    # Do not implement `get_all_vars()`, just fetch the ones we need for this check.
    # Without the GLOBAL modifier, SHOW VARIABLES displays the values that are used for
    # the current connection to MariaDB.
    sql = """
        show global variables
        where variable_name like 'join_buffer_size'
            ;
          """
    return lib.base3.coe(lib.db_mysql3.select(conn, sql))


def get_status(conn):
    # Do not implement `get_all_vars()`, just fetch the ones we need for this check.
    # Without the GLOBAL modifier, SHOW STATUS displays the values that are used for
    # the current connection to MariaDB.
    sql = """
        show global status
        where variable_name like 'Select_full_join'
            or variable_name like 'Select_range_check'
            or variable_name like 'Uptime'
            ;
          """
    return lib.base3.coe(lib.db_mysql3.select(conn, sql))


def main():
    """The main function. Hier spielt die Musik.
    """

    # logic taken from mysqltuner.pl:mysql_stats(), section # Joins, v1.9.8
    # including variable names

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    mysql_connection = {
        'user':               args.USERNAME,
        'password':           args.PASSWORD,
        'host':               args.HOSTNAME,
        'port':               args.PORT,
    }
    conn = lib.base3.coe(lib.db_mysql3.connect(mysql_connection))
    lib.base3.coe(lib.db_mysql3.check_select_privileges(conn))
    myvar = lib.db_mysql3.lod2dict(get_vars(conn))

    # init some vars
    perfdata = ''
    mycalc = {}
    mystat = lib.db_mysql3.lod2dict(get_status(conn))
    lib.db_mysql3.close(conn)

    # calculations
    mycalc['joins_without_indexes'] = int(mystat['Select_range_check']) + int(mystat['Select_full_join'])
    mycalc['joins_without_indexes_per_day'] = round(mycalc['joins_without_indexes'] / (int(mystat['Uptime']) / 86400), 1)

    # Joins
    if mycalc['joins_without_indexes_per_day'] > 250:
        state = STATE_WARN
        msg = '{} joins performed without indexes{}. Set join_buffer_size > {}, or always use indexes with JOINs. Raise the join_buffer_size until JOINs not using indexes are found.'.format(
            mycalc['joins_without_indexes'],
            lib.base3.state2str(state, prefix=' '),
            myvar['join_buffer_size'],
        )
    else:
        state = STATE_OK
        msg = 'Everything is ok.'

    perfdata += lib.base3.get_perfdata('mysql_join_buffer_size', myvar['join_buffer_size'], 'B', None, None, 0, None)
    
    perfdata += lib.base3.get_perfdata('mysql_select_full_join', mystat['Select_full_join'], 'c', None, None, 0, None)
    perfdata += lib.base3.get_perfdata('mysql_select_range_check', mystat['Select_range_check'], 'c', None, None, 0, None)
    perfdata += lib.base3.get_perfdata('mysql_uptime', mystat['Uptime'], 's', None, None, 0, None)

    perfdata += lib.base3.get_perfdata('mysql_joins_without_indexes', mycalc['joins_without_indexes'], 'c', None, None, 0, None)
    perfdata += lib.base3.get_perfdata('mysql_joins_without_indexes_per_day', mycalc['joins_without_indexes_per_day'], None, None, None, 0, None)

    # over and out
    lib.base3.oao(msg, state, perfdata, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base3.cu()
