#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_OK

TESTS = [
    {
        'id': 'ok-disks-healthy',
        'test': 'stdout/disks-healthy,,0',
        'params': '--device-id=1 --password=pass --url=https://localhost --username=admin',
        'assert-retc': STATE_OK,
        'assert-in': [
            'Everything is ok.',
            'UUID         ! Location ! Manufacturer ! Model            '
            '! SerialNumber         ! Abrasion% ! Progress% ! Runtime ! Temp ! Health ! ',
            '-------------+----------+--------------+------------------'
            '+----------------------+-----------+-----------+---------+------+--------+-----',
            '10:134234112 ! DAE000.0 ! HUAWEI       ! HSSD-D7294DL7T6E '
            '! 12345678             ! 67        ! 0         ! 4M 2W   ! 36   ! [OK]   ! [OK]',
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../huawei-dorado-disk'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
