version = "2.0"

[[packages]]
name = "bash"
[[packages.conditions]]
key = "evr"
comparator = "="
value = "5.3.9-3.fc44"

[[packages]]
name = "glibc"
[[packages.conditions]]
key = "evr"
comparator = "="
value = "2.42-6.fc44"
