apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: php-fpm-status
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: PHP-FPM Status
  uid: linuxfabrik-monitoring-plugins-php-fpm-status
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*php-fpm-status.*/
      current:
        text: cmd-check-php-fpm-status
        value: cmd-check-php-fpm-status
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query
    - label: Pool
      name: pool
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "metric" WHERE hostname = '$hostname' AND service = '$service'
      regex: /^(\S+)_saturation$/
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: PHP-FPM Status - Request Rate ($pool)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: false
        decimals: 1
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ${pool}_accepted_conn_rate
      refId: accepted conn
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_accepted_conn_rate


  - title: PHP-FPM Status - Request Rate ($pool) - Last
    type: stat
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        decimals: 0
        min: 0
        noValue: '0'
        unit: short
    options:
      colorMode: none
      graphMode: none
      reduceOptions:
        calcs:
        - last
        fields: /req\/s$/
        values: false
      textMode: auto

    targets:

    - alias: ${pool}_accepted_conn_rate
      refId: accepted conn last
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_accepted_conn_rate


  - title: PHP-FPM Status - Processes ($pool)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: false
        decimals: 1
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ${pool}_active_processes
      refId: active processes
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_active_processes
    - alias: ${pool}_idle_processes
      refId: idle processes
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_idle_processes


  - title: PHP-FPM Status - New Slow Requests ($pool)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: false
        decimals: 0
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ${pool}_slow_requests_delta
      refId: slow requests delta
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_slow_requests_delta


  - title: PHP-FPM Status - Queue ($pool)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: false
        decimals: 1
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ${pool}_listen_queue
      refId: listen queue
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_listen_queue
    - alias: ${pool}_max_listen_queue
      refId: max listen queue
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_max_listen_queue
    - alias: ${pool}_listen_queue_len
      refId: listen queue len
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_listen_queue_len


  - title: PHP-FPM Status - Saturation ($pool)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: false
        decimals: 0
        max: 110
        min: 0
        unit: percent
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ${pool}_saturation
      refId: saturation
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_saturation


  - title: PHP-FPM Status - Uptime ($pool)
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 24
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: false
        decimals: 0
        min: 0
        unit: s
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ${pool}_uptime
      refId: start since
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: ${pool}_start_since