#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

"""Integration tests for the keycloak-stats check plugin.

See check-plugins/keycloak-version/unit-test/run for the reference
testcontainers-python pattern that this test mirrors.
"""

import os
import subprocess
import sys
import unittest

sys.path.insert(0, '..')

import lib.lftest
from lib.globals import STATE_CRIT, STATE_OK, STATE_WARN


IMAGES = [
    ('quay.io/keycloak/keycloak:18.0.2', 'v18'),
    ('quay.io/keycloak/keycloak:19.0.3', 'v19'),
    ('quay.io/keycloak/keycloak:20.0.5', 'v20'),
    ('quay.io/keycloak/keycloak:21.1.2', 'v21'),
    ('quay.io/keycloak/keycloak:22.0.5', 'v22'),
    ('quay.io/keycloak/keycloak:23.0.7', 'v23'),
    ('quay.io/keycloak/keycloak:24.0.5', 'v24'),
    ('quay.io/keycloak/keycloak:25.0.6', 'v25'),
    ('quay.io/keycloak/keycloak:26.6', 'v26'),
]


class TestCheck(unittest.TestCase):
    pass


def _check_image(test, image_pair):
    """Spin up one Keycloak image and run the plugin against the API."""
    image, version_tag = image_pair
    print(f'\n=== Testing {image} ===', flush=True)
    with lib.lftest.run_container(
        image,
        env={
            'KEYCLOAK_ADMIN': 'admin',
            'KEYCLOAK_ADMIN_PASSWORD': 'admin',
        },
        ports=[8080],
        command='start-dev',
        wait_log='Listening on:',
        wait_log_timeout=180,
    ) as container:
        url = 'http://{}:{}'.format(
            container.get_container_host_ip(),
            container.get_exposed_port(8080),
        )
        cmd = [
            'python3',
            '../keycloak-stats',
            f'--url={url}',
            '--username=admin',
            '--password=admin',
        ]
        print(f'Run plugin: {" ".join(cmd)}', flush=True)
        result = subprocess.run(
            cmd,
            cwd=os.path.dirname(os.path.abspath(__file__)),
            capture_output=True,
            text=True,
        )
        combined = result.stdout + result.stderr
        print(f'Script output:\n{combined.strip()}', flush=True)

        # The plugin reports uptime, user, java version etc. Just
        # check that it produced the "running under user `keycloak`;
        # Java v..." summary shape.
        test.assertRegex(combined, r'running under user `keycloak`;\s*Java v')
        test.assertIn(result.returncode, (STATE_OK, STATE_WARN, STATE_CRIT))


lib.lftest.attach_each(TestCheck, IMAGES, _check_image, id_func=lambda it: it[1])


if __name__ == '__main__':
    unittest.main()
