#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

"""See the check's README for more details."""

import argparse
import sys

import lib.args
import lib.base
import lib.db_mysql
import lib.human
from lib.globals import STATE_OK, STATE_UNKNOWN, STATE_WARN

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2026041201'

DESCRIPTION = """Checks the rate of table locks that had to wait in MySQL/MariaDB. A high wait rate
indicates contention between concurrent queries.
Alerts when the lock wait rate is too high."""

DEFAULT_DEFAULTS_FILE = '/var/spool/icinga2/.my.cnf'
DEFAULT_DEFAULTS_GROUP = 'client'
DEFAULT_TIMEOUT = 3


def parse_args():
    """Parse command line arguments using argparse."""
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V',
        '--version',
        action='version',
        version=f'%(prog)s: v{__version__} by {__author__}',
    )

    parser.add_argument(
        '--always-ok',
        help=lib.args.help('--always-ok'),
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '--defaults-file',
        help='MySQL/MariaDB cnf file to read parameters like user, host and password from (instead of specifying them on the command line). '
        'Example: `/var/spool/icinga2/.my.cnf`. '
        'Default: %(default)s',
        dest='DEFAULTS_FILE',
        default=DEFAULT_DEFAULTS_FILE,
    )

    parser.add_argument(
        '--defaults-group',
        help=lib.args.help('--defaults-group') + ' Default: %(default)s',
        dest='DEFAULTS_GROUP',
        default=DEFAULT_DEFAULTS_GROUP,
    )

    parser.add_argument(
        '--timeout',
        help=lib.args.help('--timeout') + ' Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    args, _ = parser.parse_known_args()
    return args


def get_status(conn):
    # Do not implement `get_all_vars()`, just fetch the ones we need for this check.
    # Without the GLOBAL modifier, SHOW STATUS displays the values that are used for
    # the current connection to MariaDB.
    sql = """
        show global status
        where variable_name like 'Table_locks_immediate'
            or variable_name like 'Table_locks_waited'
            ;
          """
    return lib.base.coe(lib.db_mysql.select(conn, sql))


def main():
    """The main function. This is where the magic happens."""

    # logic taken from mysqltuner.pl:mysql_stats(), section # Table locks, v1.9.8
    # including variable names

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    mysql_connection = {
        'defaults_file': args.DEFAULTS_FILE,
        'defaults_group': args.DEFAULTS_GROUP,
        'timeout': args.TIMEOUT,
    }
    conn = lib.base.coe(lib.db_mysql.connect(mysql_connection))
    lib.base.coe(lib.db_mysql.check_select_privileges(conn))

    mystat = lib.db_mysql.lod2dict(get_status(conn))
    lib.db_mysql.close(conn)

    # init some vars
    state = STATE_OK
    perfdata = ''

    # calculations
    mycalc = {}
    if int(mystat['Table_locks_immediate']) > 0:
        if int(mystat['Table_locks_waited']) == 0:
            mycalc['pct_table_locks_immediate'] = 100
        else:
            mycalc['pct_table_locks_immediate'] = round(
                int(mystat['Table_locks_immediate'])
                / (
                    int(mystat['Table_locks_waited'])
                    + int(mystat['Table_locks_immediate'])
                )
                * 100,
                1,
            )
    else:
        mycalc['pct_table_locks_immediate'] = 0

    # Table locks
    total_locks = int(mystat['Table_locks_immediate']) + int(mystat['Table_locks_waited'])
    msg = (
        f'{mycalc["pct_table_locks_immediate"]}% table locks'
        f' acquired immediately'
        f' ({lib.human.number2human(mystat["Table_locks_immediate"])}'
        f' immediate /'
        f' {lib.human.number2human(total_locks)}'
        f' locks)'
    )
    if mycalc['pct_table_locks_immediate'] < 95:
        state = STATE_WARN

        # build the message
        msg += (
            f'{lib.base.state2str(state, prefix=" ")}'
            f'. Optimize queries and/or use InnoDB'
            f' to reduce lock wait.'
        )
    else:
        msg += '.'

    perfdata += lib.base.get_perfdata(
        'mysql_table_locks_immediate',
        mystat['Table_locks_immediate'],
        uom='c',
        _min=0,
    )
    perfdata += lib.base.get_perfdata(
        'mysql_table_locks_waited',
        mystat['Table_locks_waited'],
        uom='c',
        _min=0,
    )

    perfdata += lib.base.get_perfdata(
        'mysql_pct_table_locks_immediate',
        mycalc['pct_table_locks_immediate'],
        uom='%',
        _min=0,
        _max=100,
    )

    # over and out
    lib.base.oao(msg, state, perfdata, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception:
        lib.base.cu()
