#! /usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""Have a look at the check's README for further details.
"""

import os

# considering a virtual environment
ACTIVATE_THIS = False
venv_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'monitoring-plugins-venv3')
if os.path.exists(venv_path):
    ACTIVATE_THIS = os.path.join(venv_path, 'bin/activate_this.py')

if os.getenv('MONITORING_PLUGINS_VENV3'):
    ACTIVATE_THIS = os.path.join(os.getenv('MONITORING_PLUGINS_VENV3') + 'bin/activate_this.py')

if ACTIVATE_THIS and os.path.isfile(ACTIVATE_THIS):
    exec(open(ACTIVATE_THIS).read(), {'__file__': ACTIVATE_THIS}) # pylint: disable=W0122


import argparse # pylint: disable=C0413
import sys # pylint: disable=C0413

import lib.args3 # pylint: disable=C0413
import lib.base3 # pylint: disable=C0413
import lib.human3 # pylint: disable=C0413
import lib.nodebb3 # pylint: disable=C0413
import lib.test3 # pylint: disable=C0413
import lib.time3 # pylint: disable=C0413
from lib.globals3 import STATE_OK, STATE_UNKNOWN # pylint: disable=C0413


__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2022071201'

DESCRIPTION = """Get NodeBB post settings."""

DEFAULT_INSECURE = False
DEFAULT_TIMEOUT = 3
DEFAULT_URL = 'http://localhost:4567/forum'


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='%(prog)s: v{} by {}'.format(__version__, __author__)
    )

    parser.add_argument(
        '--insecure',
        help='This option explicitly allows to perform "insecure" SSL connections. Default: %(default)s',
        dest='INSECURE',
        action='store_true',
        default=DEFAULT_INSECURE,
    )

    parser.add_argument(
        '--test',
        help='For unit tests. Needs "path-to-stdout-file,path-to-stderr-file,expected-retc".',
        dest='TEST',
        type=lib.args3.csv,
    )

    parser.add_argument(
        '--timeout',
        help='Network timeout in seconds. Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    parser.add_argument(
        '-p', '--token',
        help='NodeBB API Bearer token.',
        dest='TOKEN',
        required=True,
    )

    parser.add_argument(
        '--url',
        help='NodeBB API URL. Default: %(default)s',
        dest='URL',
        default=DEFAULT_URL,
    )

    return parser.parse_args()


def main():
    """The main function. Hier spielt die Musik.
    """

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # fetch data
    if args.TEST is None:
        result = lib.nodebb3.get_data(args, '/api/admin/settings/post')
    else:
        # do not call the command, put in test data
        import json
        stdout, stderr, retc = lib.test3.test(args.TEST)
        result = json.loads(stdout)

    # init some vars
    msg = ''
    perfdata = ''
    table_data = []

    # analyze data
    for post in result['groupsExemptFromPostQueue']:
        post['createtime'] = post['createtime'] / 1000
        post['createtimeiso'] = '{} ({} ago)'.format(
            lib.time3.epoch2iso(post['createtime']),
            lib.human3.seconds2human(lib.time3.now(as_type='epoch') - (post['createtime'])),
        )
        table_data.append(post)

    # build the message
    msg += '{} {}'.format(
        len(result['groupsExemptFromPostQueue']),
        lib.txt3.pluralize('group', len(result['groupsExemptFromPostQueue'])),
    )
    try:
        msg += ', newest group: "{}" ({}) with {} members (created {} ago)'.format(
            result['groupsExemptFromPostQueue'][0]['name'],
            'private' if result['groupsExemptFromPostQueue'][0]['private'] else 'public',
            result['groupsExemptFromPostQueue'][0]['memberCount'],
            result['groupsExemptFromPostQueue'][0]['createtimeiso'],
        )
    except:
        pass
    msg += '\n\n'

    perfdata += lib.base3.get_perfdata('posts', len(result['groupsExemptFromPostQueue']), None, None, None, 0, None)

    if table_data:
        keys = [
          'createtimeiso',
          'slug',
          'memberCount',
        ]
        headers = [
          'createtime',
          'slug',
          'memberCount',
        ]
        msg += lib.base3.get_table(table_data, keys, header=headers)

    # over and out
    lib.base3.oao(msg, STATE_OK, perfdata)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base3.cu()
