#!/usr/bin/env python

from lib.globals import *

import lib.base

import unittest

        
class TestCheck(unittest.TestCase):

    def test_ping_127_0_0_1(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname 127.0.0.1')
        self.assertRegexpMatches(stdout, r'^PING 127\.0\.0\.1 \(127\.0\.0\.1\): ')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_OK)

    def test_ping_localhost(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname localhost')
        self.assertRegexpMatches(stdout, r'^PING localhost\(localhost \(::1\)\): ')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_OK)

    def test_ping_localhost_localdomain(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname localhost.localdomain')
        self.assertRegexpMatches(stdout, r'^PING localhost\.localdomain\(localhost \(::1\)\): ')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_OK)

    def test_ping_localhost_loc(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname localhost.loc')
        self.assertRegexpMatches(stdout, r'^ping: localhost.loc: Name or service not known')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_UNKNOWN)

    def test_ping_www_linuxfabrik_ch(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname www.linuxfabrik.ch')
        self.assertRegexpMatches(stdout, r'^PING www\.linuxfabrik\.ch \(')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_OK)

    def test_ping_1_2_3_4_5_6(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname 1.2.3.4.5.6')
        self.assertRegexpMatches(stdout, r'^ping: 1.2.3.4.5.6: Name or service not known')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_UNKNOWN)

    def test_ping_99_99_99_99(self):
        stdout, stderr, retc = lib.base.shell_exec('./ping --hostname 99.99.99.99')
        self.assertRegexpMatches(stdout, r'^Destination Host Unreachable\. PING 99\.99\.99\.99')
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_CRIT)
   

if __name__ == '__main__':
    unittest.main()