apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: mysql-innodb-buffer-pool-instances
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: MySQL InnoDB Buffer Pool Instances
  uid: linuxfabrik-monitoring-plugins-mysql-innodb-buffer-pool-instances
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*mysql-innodb-buffer-pool-instances.*/
      current:
        text: cmd-check-mysql-innodb-buffer-pool-instances
        value: cmd-check-mysql-innodb-buffer-pool-instances
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: MySQL InnoDB Buffer Pool - Instances
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: short
      overrides:
      - matcher:
          id: byName
          options: mysql_innodb_buffer_pool_instances
        properties:
        - id: displayName
          value: innodb_buffer_pool_instances
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_innodb_buffer_pool_instances
      refId: mysql_innodb_buffer_pool_instances
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_innodb_buffer_pool_instances


  - title: MySQL InnoDB Buffer Pool - Size
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        min: 0
        unit: bytes
      overrides:
      - matcher:
          id: byName
          options: mysql_innodb_buffer_pool_size
        properties:
        - id: displayName
          value: innodb_buffer_pool_size
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_innodb_buffer_pool_size
      refId: mysql_innodb_buffer_pool_size
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_innodb_buffer_pool_size
