apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: wordpress-checksums
spec:
  schemaVersion: 42
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: WordPress Checksums
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*wordpress-checksums.*/
      current:
        text: cmd-check-wordpress-checksums
        value: cmd-check-wordpress-checksums
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: Checksum Violations
    type: timeseries
    gridPos:
      h: 8
      w: 24
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - min
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: core_modified
      refId: wordpress-checksums-core_modified
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: core_modified

    - alias: core_added
      refId: wordpress-checksums-core_added
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: core_added

    - alias: core_missing
      refId: wordpress-checksums-core_missing
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: core_missing

    - alias: plugins_modified
      refId: wordpress-checksums-plugins_modified
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: plugins_modified

    - alias: plugins_added
      refId: wordpress-checksums-plugins_added
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: plugins_added

    - alias: plugins_missing
      refId: wordpress-checksums-plugins_missing
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: plugins_missing

  - title: Files Verified
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - min
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: files_checked
      refId: wordpress-checksums-files_checked
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: files_checked

  - title: Components Not Verified
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - min
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: components_unverified
      refId: wordpress-checksums-components_unverified
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: components_unverified
