---
variants:
  - linux
  - sudo

overwrites:
  '["ServiceTemplate"]["tpl-service-nginx-security"]["check_interval"]': 86400
  '["ServiceTemplate"]["tpl-service-nginx-security"]["enable_perfdata"]': true
  '["ServiceTemplate"]["tpl-service-nginx-security"]["retry_interval"]': 3600
