#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_CRIT
import lib.lftest


TESTS = [
    {
        'id': 'crit-controller-health-critical',
        'test': 'stdout/controller-health-critical,,0',
        'params': '--device-id=1 --password=pass --url=https://localhost --username=admin',
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'There are critical errors.',
            'UUID   ! Location ! Model                               ! Role      '
            '! Master ! CPU (%) ! Mem (%) ! Volt ! Health     ! Running',
            '-------+----------+-------------------------------------+-----------'
            '+--------+---------+---------+------+------------+--------',
            '207:0A ! CTE0.A   ! Unknown                             ! Primary   '
            '! -      ! 3       ! 75      ! 120  ! [CRITICAL] ! [OK]   ',
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../huawei-dorado-controller'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
