apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: sshd-logfile
spec:
  schemaVersion: 42
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: sshd Logfile
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*sshd-logfile.*/
      current:
        text: cmd-check-sshd-logfile
        value: cmd-check-sshd-logfile
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: sshd Logfile - Failed Logins
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: sshd_access_denials
      refId: sshd_access_denials
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_access_denials

    - alias: sshd_auth_failures
      refId: sshd_auth_failures
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_auth_failures

    - alias: sshd_invalid_users
      refId: sshd_invalid_users
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_invalid_users

  - title: sshd Logfile - Refused Connections
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: sshd_aborted_connections
      refId: sshd_aborted_connections
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_aborted_connections

    - alias: sshd_throttled_connections
      refId: sshd_throttled_connections
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_throttled_connections

  - title: sshd Logfile - Server Events
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: sshd_child_crashes
      refId: sshd_child_crashes
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_child_crashes

    - alias: sshd_host_key_problems
      refId: sshd_host_key_problems
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_host_key_problems

    - alias: sshd_key_file_refusals
      refId: sshd_key_file_refusals
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_key_file_refusals

    - alias: sshd_revoked_keys
      refId: sshd_revoked_keys
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_revoked_keys

    - alias: sshd_root_login_refusals
      refId: sshd_root_login_refusals
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_root_login_refusals

    - alias: sshd_startup_failures
      refId: sshd_startup_failures
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_startup_failures

  - title: sshd Logfile - Lifecycle
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: none
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: sshd_logins
      refId: sshd_logins
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_logins

    - alias: sshd_restarts
      refId: sshd_restarts
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_restarts

    - alias: sshd_shutdowns
      refId: sshd_shutdowns
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_shutdowns

    - alias: sshd_startups
      refId: sshd_startups
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_startups

  - title: sshd Logfile - Size
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        min: 0
        unit: bytes
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: sshd_logfile_size
      refId: sshd_logfile_size
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: sshd_logfile_size
