#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_OK, STATE_UNKNOWN, STATE_WARN

TESTS = [
    {
        'id': 'ok-interfaces-healthy',
        'test': 'stdout/interfaces-healthy,,0',
        'params': '--device-id=1 --password=linuxfabrik --url=https://localhost --username=admin',
        'assert-retc': STATE_OK,
        'assert-in': [
            'Everything is ok.',
            'UUID       ! Location     ! Model                                 '
            '! RunMode   ! LED ! Health     ! Running     ! State',
            '-----------+--------------+---------------------------------------+'
            '-----------+-----+------------+-------------+------',
            '209:0A.1   ! CTE0.A.IOM1  ! Unknown                               '
            '! FC        ! Off ! Normal (1) ! Running (2) ! [OK] ',
            '209:0.128  ! CTE0.IOM.H0  ! 2 ports FE 100 Gbit/s ETH I/O module  '
            '! Ethernet  ! Off ! Normal (1) ! Running (2) ! [OK] ',
            '209:0.129  ! CTE0.IOM.H1  ! 2 ports FE 100 Gbit/s ETH I/O module  '
            '! Ethernet  ! Off ! Normal (1) ! Running (2) ! [OK]',
            '209:0.134  ! CTE0.IOM.H6  ! 2 ports BE 100 Gbit/s RDMA I/O module '
            '! RDMA/RoCE ! Off ! Normal (1) ! Running (2) ! [OK] ',
            '209:0.135  ! CTE0.IOM.H7  ! 2 ports BE 100 Gbit/s RDMA I/O module '
            '! RDMA/RoCE ! Off ! Normal (1) ! Running (2) ! [OK] ',
            '209:0.140  ! CTE0.IOM.H12 ! 2 ports FE 100 Gbit/s ETH I/O module  '
            '! Ethernet  ! Off ! Normal (1) ! Running (2) ! [OK] ',
            '209:0.141  ! CTE0.IOM.H13 ! 2 ports FE 100 Gbit/s ETH I/O module  '
            '! Ethernet  ! Off ! Normal (1) ! Running (2) ! [OK] ',
        ],
        # Status codes are all a module has, and the state already carries them, so
        # there is no performance data and no pipe that would introduce it.
        'assert-not-in': ['_health_status', '_running_status', '|'],
    },
    {
        # LIGHTSTATUS and RUNMODE are optional fields. A firmware that leaves them out
        # used to end the whole check in a traceback instead of reporting the state of
        # every module it did describe.
        'id': 'ok-interface-without-optional-fields',
        'test': 'stdout/interface-without-optional-fields,,0',
        'params': '--password=linuxfabrik --url=https://localhost --username=admin',
        'assert-retc': STATE_OK,
        'assert-in': ['Everything is ok.', 'Unknown'],
        'assert-not-in': ['Unknown column', 'Traceback'],
    },
    {
        # A module that stays in power-on is not carrying traffic. Real records
        # (V700R001C10SPH128, Dorado 6000 V6), the second one set to powering on (12).
        'id': 'warn-interface-powering-on',
        'test': 'stdout/interfaces-one-powering-on,,0',
        'params': '--device-id=1 --password=linuxfabrik --url=https://localhost --username=admin',
        'assert-retc': STATE_WARN,
        'assert-in': [
            'There are warnings.',
            '! Normal (1) ! Running (2)      ! [OK]',
            '! Normal (1) ! Powering on (12) ! [WARNING]',
        ],
    },
    {
        # An appliance always has interface modules. An empty list means the query
        # never reached them, which must not read as a healthy inventory.
        'id': 'unknown-no-interface-modules',
        'test': 'stdout/no-interface-modules,,0',
        'params': '--device-id=1 --password=linuxfabrik --url=https://localhost --username=admin',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['reported no interface modules.'],
    },
]


class TestCheck(unittest.TestCase):
    check = '../huawei-dorado-interface'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
