#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_OK, STATE_UNKNOWN, STATE_WARN
import lib.lftest


TESTS = [
    {
        'id': 'unknown-invalid-regex',
        'test': 'stdout/windows-services-mixed,,',
        'params': "--service '*'",
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['Invalid regex "*": nothing to repeat at position 0'],
    },
    {
        'id': 'ok-bfe-running',
        'test': 'stdout/windows-services-mixed,,0',
        'params': "--service='^bfe' --status=running --warning=1:1",
        'assert-retc': STATE_OK,
        'assert-in': [
            "Everything is ok. 1 service named r`^bfe` and start type ['automatic'] "
            "found, 1 in status ['running'] (thresholds 1:1/None).",
        ],
    },
    {
        'id': 'warn-win-services-stopped',
        'test': 'stdout/windows-services-mixed,,0',
        'params': (
            "--service='Win.*' --starttype=automatic --status=continue_pending "
            '--status=pause_pending --status=paused --status=start_pending '
            '--status=stop_pending --status=stopped --warning 0'
        ),
        'assert-retc': STATE_WARN,
        'assert-in': [
            "3 services named r`Win.*` and start type ['automatic'] found, "
            "1 in status ['continue_pending', 'pause_pending', 'paused', "
            "'start_pending', 'stop_pending', 'stopped'] (thresholds 0/None) [WARNING].",
        ],
    },
]


class TestCheck(unittest.TestCase):

    check = '../service'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
