[cmd-check-network-io]
dashboard = "Network I/O"
panelId = "2,3,4"
orgId = ""
dashboarduid = "network-io"
; just show the first panels, until repeatable works correctly
; repeatable = "yes"
; nmetrics = "10"

[cmd-check-network-io-windows]
dashboard = "Network I/O - Windows"
panelId = "2,3,4"
orgId = ""
dashboarduid = "network-io"
; just show the first panels, until repeatable works correctly
; repeatable = "yes"
; nmetrics = "10"

[cmd-check-network-io-windows-python]
dashboard = "Network I/O - Windows"
panelId = "2,3,4"
orgId = ""
dashboarduid = "network-io"
; just show the first panels, until repeatable works correctly
; repeatable = "yes"
; nmetrics = "10"
