#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""See the check's README for more details.
"""

import argparse  # pylint: disable=C0413
import re  # pylint: disable=C0413
import sys  # pylint: disable=C0413

import lib.base  # pylint: disable=C0413
import lib.version  # pylint: disable=C0413
from lib.globals import (STATE_UNKNOWN) # pylint: disable=C0413

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2023051201'

DESCRIPTION = 'Tracks if Fedora is EOL.'

# from https://endoflife.date/api/fedora.json
ENDOFLIFE_DATE = [
  {
    "cycle": "38",
    "latest": "38",
    "eol": "2025-05-18",
    "latestReleaseDate": "2023-04-18",
    "releaseDate": "2023-04-18",
    "lts": False
  },
  {
    "cycle": "37",
    "latest": "37",
    "eol": "2023-12-15",
    "latestReleaseDate": "2022-11-15",
    "releaseDate": "2022-11-15",
    "lts": False
  },
  {
    "cycle": "36",
    "latest": "36",
    "eol": "2023-05-18",
    "latestReleaseDate": "2022-05-10",
    "releaseDate": "2022-05-10",
    "lts": False
  },
  {
    "cycle": "35",
    "latest": "35",
    "eol": "2022-12-13",
    "latestReleaseDate": "2021-11-02",
    "releaseDate": "2021-11-02",
    "lts": False
  },
  {
    "cycle": "34",
    "latest": "34",
    "eol": "2022-06-07",
    "latestReleaseDate": "2021-04-27",
    "releaseDate": "2021-04-27",
    "lts": False
  },
  {
    "cycle": "33",
    "latest": "33",
    "eol": "2021-11-30",
    "latestReleaseDate": "2020-10-27",
    "releaseDate": "2020-10-27",
    "lts": False
  },
  {
    "cycle": "32",
    "latest": "32",
    "eol": "2021-05-25",
    "latestReleaseDate": "2020-04-28",
    "releaseDate": "2020-04-28",
    "lts": False
  },
  {
    "cycle": "31",
    "latest": "31",
    "eol": "2020-11-30",
    "latestReleaseDate": "2019-10-29",
    "releaseDate": "2019-10-29",
    "lts": False
  },
  {
    "cycle": "30",
    "latest": "30",
    "eol": "2020-05-26",
    "latestReleaseDate": "2019-04-30",
    "releaseDate": "2019-04-30",
    "lts": False
  },
  {
    "cycle": "29",
    "latest": "29",
    "eol": "2019-11-26",
    "latestReleaseDate": "2018-10-30",
    "releaseDate": "2018-10-30",
    "lts": False
  },
  {
    "cycle": "28",
    "latest": "28",
    "eol": "2019-05-28",
    "latestReleaseDate": "2018-05-01",
    "releaseDate": "2018-05-01",
    "lts": False
  }
]


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='%(prog)s: v{} by {}'.format(__version__, __author__)
    )

    parser.add_argument(
        '--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    return parser.parse_args()


def main():
    """The main function. Hier spielt die Musik.
    """

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # fetch data
    installed_version = lib.version.get_os_info()
    state, msg = lib.version.check_eol(
        ENDOFLIFE_DATE,
        re.search(r'x (\d+)', installed_version).group(1),
    )

    # over and out
    lib.base.oao(
        '{} ({})'.format(installed_version, msg),
        state,
        lib.base.get_perfdata(
            'fedora-version',
            re.search(r'x (\d+)', installed_version).group(1),
            None,
            None,
            None,
            0,
            None,
        ),
        always_ok=args.ALWAYS_OK,
    )


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base.cu()
