#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

"""Unit tests for the mastodon-version check plugin.

`--test` stands in for what `podman exec <container> cat` prints of
`/opt/mastodon/lib/mastodon/version.rb` in the running Mastodon container.
`stdout/version-rb-4-7-2` was read out of `ghcr.io/mastodon/mastodon:latest` on
2026-10-01; `stdout/version-rb-without-patch` is the same file with the `patch`
method removed.

The verdict comes from the endoflife.date feed, which the fixtures do not stand in
for, so the testcases pin the parsed version and leave the state alone.
"""

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_UNKNOWN

TESTS = [
    {
        'id': 'parses-version-rb-4-7-2',
        'test': 'stdout/version-rb-4-7-2,,0',
        'assert-in': ['Mastodon v4.7.2'],
    },
    {
        'id': 'unknown-version-rb-without-patch',
        'test': 'stdout/version-rb-without-patch,,0',
        'assert-retc': STATE_UNKNOWN,
        'assert-in': ['Mastodon not found', '--path', '--user'],
    },
]


class TestCheck(unittest.TestCase):
    check = '../mastodon-version'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
