#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_OK, STATE_WARN
import lib.lftest


BASE_PARAMS = '--repo=test --password-file=test'


TESTS = [
    {
        'id': 'ok-check-passed',
        'test': 'stdout/check-passed,,',
        'params': BASE_PARAMS,
        'assert-retc': STATE_OK,
        'assert-in': ['Everything is ok'],
    },
    {
        'id': 'warn-check-with-warnings',
        'test': 'stdout/check-with-warnings,,',
        'params': BASE_PARAMS,
        'assert-retc': STATE_WARN,
        'assert-in': ['There are warnings'],
    },
]


class TestCheck(unittest.TestCase):

    check = '../restic-check'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
