#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

"""See the check's README for more details."""

import argparse
import sys

import lib.args
import lib.base
import lib.txt
import lib.wildfly
from lib.globals import STATE_CRIT, STATE_OK, STATE_UNKNOWN, STATE_WARN

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2026040801'

DESCRIPTION = """Checks the deployment status of applications on a WildFly/JBoss AS server via its HTTP
management API. Alerts when any deployment is not in the expected enabled state."""

DEFAULT_INSECURE = False
DEFAULT_NO_PROXY = False
DEFAULT_TIMEOUT = 3
DEFAULT_URL = 'http://localhost:9990'
DEFAULT_USERNAME = 'wildfly-monitoring'


def parse_args():
    """Parse command line arguments using argparse."""
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V',
        '--version',
        action='version',
        version=f'%(prog)s: v{__version__} by {__author__}',
    )

    parser.add_argument(
        '--always-ok',
        help=lib.args.help('--always-ok'),
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '--deployment',
        help='Application deployment name to check. '
        'Can be specified multiple times. '
        'If not specified, all deployments are checked.',
        dest='DEPLOYMENT',
        action='append',
        default=None,
    )

    parser.add_argument(
        '--insecure',
        help=lib.args.help('--insecure'),
        dest='INSECURE',
        action='store_true',
        default=DEFAULT_INSECURE,
    )

    parser.add_argument(
        '--instance',
        help='WildFly instance (server-config) to check when running in domain mode.',
        dest='INSTANCE',
    )

    parser.add_argument(
        '--mode',
        help='WildFly server mode. Default: %(default)s',
        dest='MODE',
        choices=['standalone', 'domain'],
        default='standalone',
    )

    parser.add_argument(
        '--no-proxy',
        help=lib.args.help('--no-proxy'),
        dest='NO_PROXY',
        action='store_true',
        default=DEFAULT_NO_PROXY,
    )

    parser.add_argument(
        '--node',
        help='WildFly node (host) when running in domain mode.',
        dest='NODE',
    )

    parser.add_argument(
        '-p',
        '--password',
        help='WildFly management API password.',
        dest='PASSWORD',
        required=True,
    )

    parser.add_argument(
        '--timeout',
        help=lib.args.help('--timeout') + ' Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    parser.add_argument(
        '--url',
        help='WildFly management API URL. Default: %(default)s',
        dest='URL',
        default=DEFAULT_URL,
    )

    parser.add_argument(
        '--username',
        help='WildFly management API username. Default: %(default)s',
        dest='USERNAME',
        default=DEFAULT_USERNAME,
        required=True,
    )

    args, _ = parser.parse_known_args()
    return args


def check_deployment_status(args):
    data = {
        'operation': 'read-attribute',
        # /deployment/*
        'address': [{'deployment': '*'}],
        'name': 'status',
        'json': 1,
    }
    res = lib.wildfly.get_data(args, data)

    # build the message
    msg = '\n\n'
    perfdata = ''
    state = STATE_OK
    deployments = 0

    for result in res:
        deployment = {k: v for d in result.get('address') for k, v in d.items()}.get(
            'deployment'
        )

        if args.DEPLOYMENT is not None:
            # filter for specific datasource
            if deployment not in args.DEPLOYMENT:
                continue

        deployments += 1
        if result.get('result') in ['OK', 'RUNNING']:
            local_state = STATE_OK
            perfdata += lib.base.get_perfdata(
                f'deployment-state-{deployment}',
                0,
                _min=0,
                _max=2,
            )
        elif result.get('result') in ['STOPPED']:
            local_state = STATE_WARN
            perfdata += lib.base.get_perfdata(
                f'deployment-state-{deployment}',
                1,
                _min=0,
                _max=2,
            )
        else:
            local_state = STATE_CRIT
            perfdata += lib.base.get_perfdata(
                f'deployment-state-{deployment}',
                2,
                _min=0,
                _max=2,
            )
        state = lib.base.get_worst(state, local_state)
        msg += f'* {deployment} is {result.get("result")}{lib.base.state2str(local_state, prefix=" ")}\n'

    if state == STATE_OK:
        msg = (
            f'{deployments} {lib.txt.pluralize("Deployment", deployments)} checked, everything is ok.'
            + msg
        )
    else:
        msg = (
            f'{deployments} {lib.txt.pluralize("Deployment", deployments)} checked, there are errors.'
            + msg
        )
    # over and out
    lib.base.oao(msg, state, perfdata, always_ok=args.ALWAYS_OK)


def main():
    """The main function. This is where the magic happens."""

    # parse the command line
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # fetch data
    # https://docs.wildfly.org/23/Admin_Guide.html
    return check_deployment_status(args)


if __name__ == '__main__':
    try:
        main()
    except Exception:
        lib.base.cu()
