#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""See the check's README for more details.
"""

import argparse  # pylint: disable=C0413
import sys  # pylint: disable=C0413

import lib.base3  # pylint: disable=C0413
import lib.db_mysql3  # pylint: disable=C0413
import lib.human3  # pylint: disable=C0413
from lib.globals3 import (STATE_OK, STATE_UNKNOWN,  # pylint: disable=C0413
                          STATE_WARN)

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2023030201'

DESCRIPTION = """Checks the number of on-disk versus in-memory temporary tables created
                 in MySQL/MariaDB."""

DEFAULT_DEFAULTS_FILE = '/var/spool/icinga2/.my.cnf'
DEFAULT_DEFAULTS_GROUP = 'client'
DEFAULT_TIMEOUT = 3


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='{0}: v{1} by {2}'.format('%(prog)s', __version__, __author__)
    )

    parser.add_argument(
        '--always-ok',
        help='Always returns OK.',
        dest='ALWAYS_OK',
        action='store_true',
        default=False,
    )

    parser.add_argument(
        '--defaults-file',
        help='Specifies a cnf file to read parameters like user, host and password from '
             '(instead of specifying them on the command line), '
             'for example `/var/spool/icinga2/.my.cnf`. Default: %(default)s',
        dest='DEFAULTS_FILE',
        default=DEFAULT_DEFAULTS_FILE,
    )

    parser.add_argument(
        '--defaults-group',
        help='Group/section to read from in the cnf file. Default: %(default)s',
        dest='DEFAULTS_GROUP',
        default=DEFAULT_DEFAULTS_GROUP,
    )

    parser.add_argument(
        '--timeout',
        help='Network timeout in seconds. Default: %(default)s (seconds)',
        dest='TIMEOUT',
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    return parser.parse_args()


def get_vars(conn):
    # Do not implement `get_all_vars()`, just fetch the ones we need for this check.
    # Without the GLOBAL modifier, SHOW VARIABLES displays the values that are used for
    # the current connection to MariaDB.
    sql = """
        show global variables
        where variable_name like 'max_heap_table_size'
            or variable_name like 'tmp_table_size'
            ;
          """
    return lib.base3.coe(lib.db_mysql3.select(conn, sql))


def get_status(conn):
    # Do not implement `get_all_vars()`, just fetch the ones we need for this check.
    # Without the GLOBAL modifier, SHOW STATUS displays the values that are used for
    # the current connection to MariaDB.
    sql = """
        show global status
        where variable_name like 'Created_tmp_disk_tables'
            or variable_name like 'Created_tmp_tables'
            ;
          """
    return lib.base3.coe(lib.db_mysql3.select(conn, sql))


def main():
    """The main function. Hier spielt die Musik.
    """

    # logic taken from mysqltuner.pl:mysql_stats(), section # Temporary tables, v1.9.8
    # including variable names

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    mysql_connection = {
        'defaults_file':  args.DEFAULTS_FILE,
        'defaults_group': args.DEFAULTS_GROUP,
        'timeout':        args.TIMEOUT,
    }
    conn = lib.base3.coe(lib.db_mysql3.connect(mysql_connection))
    lib.base3.coe(lib.db_mysql3.check_select_privileges(conn))

    myvar = lib.db_mysql3.lod2dict(get_vars(conn))
    mystat = lib.db_mysql3.lod2dict(get_status(conn))
    lib.db_mysql3.close(conn)

    # init some vars
    msg = ''
    state = STATE_OK
    perfdata = ''

    # calculations
    mycalc = {}
    if int(mystat['Created_tmp_tables']) > 0:
        if int(mystat['Created_tmp_disk_tables']) > 0:
            mycalc['pct_temp_disk'] = round(int(mystat['Created_tmp_disk_tables']) / int(mystat['Created_tmp_tables']) * 100, 1)
        else:
            mycalc['pct_temp_disk'] = 0
    mycalc['max_tmp_table_size'] = max(int(myvar['max_heap_table_size']), int(myvar['tmp_table_size']))

    # Temporary tables
    if int(mystat['Created_tmp_tables']) > 0:
        msg += '{}% temporary tables created on disk ({} on disk / {} total)'.format(
            mycalc['pct_temp_disk'],
            lib.human3.number2human(mystat['Created_tmp_disk_tables']),
            lib.human3.number2human(mystat['Created_tmp_tables']),
        )
        if mycalc['pct_temp_disk'] > 25 and mycalc['max_tmp_table_size'] < 256 * 1024 * 1024:
            state = STATE_WARN
            msg += '{}. Set tmp_table_size > {} and max_heap_table_size > {}. '.format(
                lib.base3.state2str(state, prefix=' '),
                myvar['tmp_table_size'],
                myvar['max_heap_table_size'],
            )
            msg += 'When making adjustments, make tmp_table_size/max_heap_table_size equal. '
            msg += 'Reduce your SELECT DISTINCT queries which have no LIMIT clause.'
        elif mycalc['pct_temp_disk'] > 25 and mycalc['max_tmp_table_size'] >= 256 * 1024 * 1024:
            state = STATE_WARN
            msg += '{}. Temporary table size is already large - reduce result set size. '.format(
                lib.base3.state2str(state, prefix=' '),
            )
            msg += 'Reduce your SELECT DISTINCT queries without LIMIT clauses.'
        else:
            msg += '.'
    else:
        msg = 'Everything is ok.'

    perfdata += lib.base3.get_perfdata('mysql_max_heap_table_size', myvar['max_heap_table_size'], 'B', None, None, 0, None)
    perfdata += lib.base3.get_perfdata('mysql_tmp_table_size', myvar['tmp_table_size'], 'B', None, None, 0, None)

    perfdata += lib.base3.get_perfdata('mysql_created_tmp_disk_tables', mystat['Created_tmp_disk_tables'], 'c', None, None, 0, None)
    perfdata += lib.base3.get_perfdata('mysql_created_tmp_tables', mystat['Created_tmp_tables'], 'c', None, None, 0, None)

    perfdata += lib.base3.get_perfdata('mysql_max_tmp_table_size', mycalc['max_tmp_table_size'], 'B', None, None, 0, None)
    perfdata += lib.base3.get_perfdata('mysql_pct_temp_disk', mycalc['pct_temp_disk'], '%', None, None, 0, 100)

    # over and out
    lib.base3.oao(msg, state, perfdata, always_ok=args.ALWAYS_OK)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base3.cu()
