#! /usr/bin/env python2
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://nagios-plugins.org/doc/guidelines.html

__author__  = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2020012801'

DESCRIPTION = 'Return the average system load per cpu over the last 1, 5 and 15 minutes.'

command = 'cat /proc/loadavg'

DEFAULT_WARN  = 1.15     # load divided by all cpus
DEFAULT_CRIT  = 5.00     # load divided by all cpus


#====================
from lib.globals import *

import argparse
try:
    import psutil
except ImportError, e:
    print('Python module "psutil" is not installed. Try `yum -y install epel-release;yum -y install python2-psutil`.')
    exit(STATE_UNKNOWN)

from lib.output import seconds2human, unpack_perfdata
from lib.utils import execute_command


def define_args():
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument('-c', '--critical',
        help = 'Set the critical threshold for load15 per cpu. Default: %(default)s',
        dest = 'CRIT',
        type = float,
        default = DEFAULT_CRIT,
        )

    parser.add_argument('-V', '--version',
        action = 'version',
        version = '{0}: v{1} by {2}'.format('%(prog)s', __version__, __author__)
        )

    parser.add_argument('-w', '--warning',
        help = 'Set the warning threshold for load15 per cpu. Default: %(default)s',
        dest = 'WARN',
        type = float,
        default = DEFAULT_WARN,
        )

    return parser.parse_args()


def main():
    # parse the command line, exit with UNKNOWN if it fails
    try:
        parsed = define_args()
    except SystemExit as e:
        exit(STATE_UNKNOWN)

    CRIT = float(parsed.CRIT)
    WARN = float(parsed.WARN)

    # we could get the load natively with psutil >= 5.6.2
    # but until then, we do this here:
    stdout, stderr, retc = execute_command(command)
    if (retc != 0):
        print('Bash command `{}` failed.'.format(command_cmd))
        print('Stdout: {}\nStderr: {}'.format(stdout, stderr))
        exit(STATE_UNKNOWN)

    load1, load5, load15, tmp1, tmp2 = stdout.split(' ')
    cpu_count = float(psutil.cpu_count(logical=True))

    load1 = float(load1) / cpu_count
    load5 = float(load5) / cpu_count
    load15 = float(load15) / cpu_count

    msg = ''
    perfdata = ''
    state = STATE_OK

    if load15 >= CRIT:
        state = STATE_CRIT
    elif load15 >= WARN:
        state = STATE_WARN

    msg += 'Load average per CPU: {:0.2f}, {:0.2f}, {:0.2f}'.format(load1, load5, load15)
    perfdata += unpack_perfdata('load1',  load1,  None, WARN, CRIT, 0, None)
    perfdata += unpack_perfdata('load5',  load5,  None, WARN, CRIT, 0, None)
    perfdata += unpack_perfdata('load15', load15, None, WARN, CRIT, 0, None)

    # over and out
    print(msg.strip() + '|' + perfdata.strip())
    exit(state)


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(e)
        exit(STATE_UNKNOWN)
