#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_CRIT, STATE_OK
import lib.lftest


COMMON = '--winrm-hostname=dummy --winrm-password=dummy'


TESTS = [
    {
        'id': 'crit-scope-above-critical-threshold',
        'test': 'stdout/three-scopes-two-high-usage,,0',
        'params': COMMON,
        'assert-retc': STATE_CRIT,
        'assert-in': [
            'There are one or more criticals.',
            '* 192.0.2.120: 0% used',
            '* 192.0.2.121: 83% used [WARNING]',
            '* 192.0.2.122: 91% used [CRITICAL]',
        ],
    },
    {
        'id': 'ok-garbage-output-no-scopes',
        'test': 'stdout/garbage-output,,0',
        'params': COMMON,
        'assert-retc': STATE_OK,
        'assert-in': ['Everything is ok.'],
    },
    {
        'id': 'ok-eight-scopes-all-healthy',
        'test': 'stdout/eight-scopes-all-healthy,,0',
        'params': COMMON,
        'assert-retc': STATE_OK,
        'assert-in': ['Everything is ok.'],
    },
]


class TestCheck(unittest.TestCase):

    check = '../dhcp-scope-usage'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
