#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

import sys
sys.path.append("..") # Adds higher directory to python modules path.



import unittest

from lib.globals import STATE_OK, STATE_UNKNOWN, STATE_WARN, STATE_CRIT
import lib.base
import lib.shell


class TestCheck(unittest.TestCase):

    check = '../snmp'

    # against any-any-any.csv
    def test_if_check_runs_EXAMPLE01(self):
        stdout, stderr, retc = lib.base.coe(lib.shell.shell_exec(self.check + ' --hostname 127.0.0.1 --test=stdout/EXAMPLE01,,0'))
        self.assertIn('Key                    ! Value                                             ! State', stdout)
        self.assertIn('-----------------------+---------------------------------------------------+------', stdout)
        self.assertIn('Name                   ! BRW38B1DB3B30F4                                   ! [OK]', stdout)
        self.assertIn('Location               ! Buero                                             ! [OK]', stdout)
        self.assertIn('Contact                ! postmaster@linuxfabrik.ch                         ! [OK]', stdout)
        self.assertIn('Description            ! Brother NC-350w, Firmware Ver.N  ,MID 8CA-U29-001 ! [OK]', stdout)
        self.assertIn('Uptime                 ! 5M 2W                                             ! [WARNING]', stdout)
        self.assertIn('Memory Size            ! 256.0MiB                                          ! [OK]', stdout)
        self.assertIn('NIC.1 Speed            ! 72.0Mbps                                          ! [OK]', stdout)
        self.assertIn('NIC.1 Status           ! up                                                ! [OK]', stdout)
        self.assertIn('NIC.1 Traffic sent     ! 84.6MiB                                           ! [OK]', stdout)
        self.assertIn('NIC.1 Traffic received ! 621.0MiB                                          ! [OK]', stdout)
        self.assertIn('NIC.1 Traffic          ! 705.5MiB                                          ! [OK]', stdout)

        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_WARN)

    # against any-any-any.csv
    def test_if_check_runs_EXAMPLE02(self):
        stdout, stderr, retc = lib.base.coe(lib.shell.shell_exec(self.check + ' --hostname 127.0.0.2 --test=stdout/EXAMPLE02,,0'))
        self.assertIn('Key                                ! Value                                                                                                                    ! State', stdout)
        self.assertIn('-----------------------------------+--------------------------------------------------------------------------------------------------------------------------+------', stdout)
        self.assertIn('Name                               ! switch.linuxfabrik.loc                                                                                                   ! [OK]', stdout)
        self.assertIn('Location                           ! V.01.020!XZ                                                                                                              ! [OK]', stdout)
        self.assertIn('Contact                            ! postmaster@linuxfabrik.ch                                                                                                ! [OK]', stdout)
        self.assertIn('Description                        ! Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 16.12.3a, RELEASE SOFTWARE (fc1) ! [OK]', stdout)
        self.assertIn('Uptime                             ! 4M 3W                                                                                                                    ! [WARNING]', stdout)
        self.assertIn('HOST-RESOURCES-MIB::hrMemorySize.0 ! No Such Object available on this agent at this OID                                                                       ! [UNKNOWN]', stdout)
        self.assertIn('NIC.1 Speed                        ! 1.0Gbps                                                                                                                  ! [OK]', stdout)
        self.assertIn('NIC.1 Status                       ! "down"                                                                                                                   ! [OK]', stdout)
        self.assertIn('NIC.1 Traffic sent                 ! 1.3KiB                                                                                                                   ! [OK]', stdout)
        self.assertIn('NIC.1 Traffic received             ! 4.6KiB                                                                                                                   ! [OK]', stdout)
        self.assertIn('NIC.1 Traffic                      ! 5.9KiB                                                                                                                   ! [OK]', stdout)
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_WARN)

    # against EXAMPLE03.csv
    def test_if_check_runs_EXAMPLE03(self):
        stdout, stderr, retc = lib.base.coe(lib.shell.shell_exec(self.check + ' --hostname 127.0.0.3 --test=stdout/EXAMPLE03,,0'))
        self.assertIn('Key                      ! Value        ! State', stdout)
        self.assertIn('-------------------------+--------------+----------', stdout)
        self.assertIn('System Name              ! My Appliance ! [OK]', stdout)
        self.assertIn('System Location          ! My Location  ! [OK]', stdout)
        self.assertIn('Supply Air Temperature   ! 27.0         ! [WARNING]', stdout)
        self.assertIn('Rack Inlet Temperature 1 ! 36.0         ! [CRITICAL]', stdout)
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_CRIT)


if __name__ == '__main__':
    unittest.main()