apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: network-errors
spec:
  schemaVersion: 42
  tags:
    - Linuxfabrik
    - Grizzly
    - repeating
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: Network Errors
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*network-errors.*/
      current:
        text: cmd-check-network-errors
        value: cmd-check-network-errors
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query
    - label: Metric
      name: metric
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "metric" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query
      hide: 2
      includeAll: true
      multi: true
      regex: /^([^_]+)/

  panels:

  - title: $metric
    type: row
    gridPos:
      h: 1
      w: 24
      x: 0
      y: 0
    repeat: metric
    repeatDirection: h


  - title: Network Errors - $metric - Errors per Second by Type
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 1
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 2
        mappings: []
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true

    targets:

    - alias: rx_errs
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-rx_errs
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_rx_errs_per_second/
    - alias: rx_fifo
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-rx_fifo
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_rx_fifo_per_second/
    - alias: rx_frame
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-rx_frame
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_rx_frame_per_second/
    - alias: tx_carrier
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-tx_carrier
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_tx_carrier_per_second/
    - alias: tx_errs
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-tx_errs
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_tx_errs_per_second/
    - alias: tx_fifo
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-tx_fifo
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_tx_fifo_per_second/

  - title: Network Errors - $metric - Combined Error Rate
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 1
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 2
        mappings: []
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true

    targets:

    - alias: errors
      groupBy:
      - params:
        - $interval
        type: time
      - params:
        - previous
        type: fill
      measurement: $command
      refId: network-errors-errors
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - key: metric
        operator: =~
        value: /^${metric}_errors_per_second/
