#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys
sys.path.insert(0, '..')

import unittest

from lib.globals import STATE_WARN
import lib.lftest


TESTS = [
    {
        'id': 'warn-backup-2021-06-17',
        'test': 'stdout/backup-2021-06-17,,',
        'assert-retc': STATE_WARN,
        'assert-in': ['Last Backup to [MAIL]user@example.ch at 2021-06-17 01:17:08 ('],
    },
]


class TestCheck(unittest.TestCase):

    check = '../starface-backup-status'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
