#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.md

import sys

sys.path.insert(0, '..')

import unittest

import lib.lftest
from lib.globals import STATE_OK, STATE_WARN

TESTS = [
    {
        'id': 'warn-no-server-used-v1',
        'test': 'stdout/no-server-used-v1,,0',
        'assert-retc': STATE_WARN,
        'assert-in': ['No NTP server used.'],
    },
    {
        'id': 'ok-stratum-2-synced-v1',
        'test': 'stdout/stratum-2-synced-v1,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            'NTP offset is -0.03ms, Stratum is 2',
            'remote           refid      st t when poll reach   delay   offset  jitter',
            '==============================================================================',
            '*ns3.fiberteleco 192.168.10.1     2 u  233   64   30   44.555   -0.030   4.486',
        ],
    },
    {
        'id': 'warn-no-server-used-v2',
        'test': 'stdout/no-server-used-v2,,0',
        'assert-retc': STATE_WARN,
        'assert-in': ['No NTP server used.'],
    },
    {
        'id': 'warn-no-server-used-v3',
        'test': 'stdout/no-server-used-v3,,0',
        'assert-retc': STATE_WARN,
        'assert-in': ['No NTP server used.'],
    },
    {
        'id': 'ok-stratum-2-synced-v2',
        'test': 'stdout/stratum-2-synced-v2,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            'NTP offset is -0.182ms, Stratum is 2',
            'remote           refid      st t when poll reach   delay   offset  jitter',
            '==============================================================================',
            '*185.232.69.65 ( 79.133.44.146    2 u  232  256  377    0.398   -0.182   0.170',
        ],
    },
    # A pool client with twenty peers. Two shapes that only show up on a busy
    # host: the synchronised peer is an IPv6 address that ntpq truncated to the
    # width of the remote column, and the ".POOL." rows are placeholders at
    # stratum 16 with reach 0 that must not be mistaken for peers.
    {
        'id': 'ok-twenty-peers-ipv6-and-pool',
        'test': 'stdout/twenty-peers-ipv6-and-pool,,0',
        'assert-retc': STATE_OK,
        'assert-in': [
            'NTP offset is -0.409ms, Stratum is 2',
            "'offset'=-0.409ms",
        ],
    },
    # Same fixture: stratum 2 is at the default --stratum of 6, so raising the
    # bar to 2 turns the very same reading into a warning.
    {
        'id': 'warn-twenty-peers-stratum-too-high',
        'test': 'stdout/twenty-peers-ipv6-and-pool,,0',
        'params': '--stratum=2',
        'assert-retc': STATE_WARN,
        'assert-in': ['Stratum is 2 (is >= 2'],
    },
]


class TestCheck(unittest.TestCase):
    check = '../ntp-ntpd'


lib.lftest.attach_tests(TestCheck, TESTS)


if __name__ == '__main__':
    unittest.main()
