#! /usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://git.linuxfabrik.ch/linuxfabrik-icinga-plugins/checks-linux/-/blob/master/CONTRIBUTING.md

import unittest

from lib.globals3 import STATE_OK, STATE_UNKNOWN, STATE_WARN, STATE_CRIT
import lib.base3

        
class TestCheck(unittest.TestCase):

    check = './docker-info3'

    def test_if_check_runs_EXAMPLE01(self):
        stdout, stderr, retc = lib.base3.coe(lib.base3.shell_exec(self.check + ' --test=examples/EXAMPLE01,,0'))
        self.assertIn('0 Containers (0 running, 0 paused, 0 stopped)', stdout)
        self.assertIn("'memory'=16340729856;;;0;", stdout)
        self.assertEqual(stderr, '')
        self.assertEqual(retc, STATE_OK)

    
if __name__ == '__main__':
    unittest.main()