apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: mysql-aria
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: MySQL Aria
  uid: linuxfabrik-monitoring-plugins-mysql-aria
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - label: Command
      name: command
      query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /.*mysql-aria.*/
      current:
        text: cmd-check-mysql-aria
        value: cmd-check-mysql-aria
      refresh: 1
      sort: 1
      type: query
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "$command" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: MySQL Aria - Pagecache and Index Sizes
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        min: 0
        unit: bytes
      overrides:
      - matcher:
          id: byName
          options: mysql_aria_pagecache_buffer_size
        properties:
        - id: displayName
          value: aria_pagecache_buffer_size
      - matcher:
          id: byName
          options: mysql_total_aria_indexes
        properties:
        - id: displayName
          value: Total Aria index size
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_aria_pagecache_buffer_size
      refId: mysql_aria_pagecache_buffer_size
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_aria_pagecache_buffer_size

    - alias: mysql_total_aria_indexes
      refId: mysql_total_aria_indexes
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_total_aria_indexes


  - title: MySQL Aria - Pagecache Read Activity
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 0
        min: 0
        unit: short
      overrides:
      - matcher:
          id: byName
          options: mysql_aria_pagecache_read_requests
        properties:
        - id: displayName
          value: Aria_pagecache_read_requests
      - matcher:
          id: byName
          options: mysql_aria_pagecache_reads
        properties:
        - id: displayName
          value: Aria_pagecache_reads
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_aria_pagecache_read_requests
      refId: mysql_aria_pagecache_read_requests
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_aria_pagecache_read_requests

    - alias: mysql_aria_pagecache_reads
      refId: mysql_aria_pagecache_reads
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_aria_pagecache_reads


  - title: MySQL Aria - Pagecache Hit Rate
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          drawStyle: line
          lineInterpolation: smooth
          lineWidth: 1
          pointSize: 3
          showPoints: always
          spanNulls: false
        decimals: 1
        max: 100
        min: 0
        unit: percent
      overrides:
      - matcher:
          id: byName
          options: mysql_pct_aria_keys_from_mem
        properties:
        - id: displayName
          value: Aria pagecache hit rate
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: mysql_pct_aria_keys_from_mem
      refId: mysql_pct_aria_keys_from_mem
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: mysql_pct_aria_keys_from_mem
